"""Compact six-to-ten-minute lessons prepared for September 1, 2026."""


def lesson(identifier, title, era, orientation, associations, route, locks, source_label, source_url):
    return {
        "id": identifier,
        "format": "compact-association-v1",
        "title": title,
        "era": era,
        "orientation": orientation,
        "associations": [{"label": label, "text": text} for label, text in associations],
        "iacRoute": route,
        "confusables": [{"term": term, "distinction": distinction} for term, distinction in locks],
        "sources": [{"label": source_label, "url": source_url}],
    }


LESSONS = [
    lesson(
        "POL-030", "John Winthrop", "1588-1649 | Massachusetts Bay leader",
        "A Puritan lawyer who transferred a chartered company into New England, repeatedly governed Massachusetts Bay, and framed the colony as a covenanted example watched by the world.",
        [
            ("Groton and the Cambridge Agreement, 1629", "This Suffolk landowner joined the Cambridge Agreement, whose signers promised to emigrate if the Massachusetts Bay charter and government moved with them. That transfer let the colony exercise unusual independence from London."),
            ("Governor before departure", "Company shareholders elected him governor before the migration. John Endecott had governed the small advance settlement, but this leader arrived with the much larger 1630 fleet."),
            ("The Arbella", "He crossed the Atlantic aboard this flagship in 1630. The fleet settled principally around Boston rather than remaining at the earlier Salem center."),
            ("A Model of Christian Charity", "This sermon described a community bound by mutual love and warned that failure would make the colonists a story and by-word. Its exact place of delivery is uncertain, despite its association with the Arbella."),
            ("City upon a hill", "His biblical image meant that the Puritan experiment would be publicly judged, not that Massachusetts possessed automatic national greatness. Ronald Reagan later transformed it into an optimistic American slogan."),
            ("Blessing of the Bay", "He owned this early colonial ship and participated with William Pynchon in the fur trade. Both are valuable clues beyond the famous sermon."),
            ("Roger Williams", "Although he opposed Williams's theology, he privately warned him that arrest was imminent in 1635. Williams escaped and founded Providence."),
            ("Anne Hutchinson and Henry Vane", "During the Antinomian Controversy, Hutchinson and young governor Henry Vane emphasized John Cotton's covenant-of-grace theology. This magistrate returned to office and supported Hutchinson's banishment."),
            ("The Pequot War, 1637", "He governed during the war that culminated in the Mystic massacre. That same year, the colony restricted political participation by Hutchinson's supporters."),
            ("Natural and civil liberty", "In a 1645 speech, he distinguished lawless natural liberty from civil or federal liberty exercised within a moral covenant. The distinction can open a political-thought question."),
            ("John the Younger", "His son became governor of Connecticut, led the Saybrook project, founded New London, and secured Connecticut's 1662 charter. Questions may ask for the surname shared by father and son."),
            ("The journal", "His detailed record of events from 1630 to 1649 became The History of New England. It is a major narrative source for early Massachusetts."),
            ("Repeated governorships and death", "He alternated the governorship with Endecott, Vane, Thomas Dudley, and Richard Bellingham. He died in Boston in 1649 while serving his final term."),
        ],
        {"6": ["Love and story-and-by-word passages", "Blessing of the Bay", "William Pynchon and John the Younger"], "5": ["Endecott and Henry Vane", "Roger Williams warning", "A Model of Christian Charity"], "4": ["Four-time governing periods", "Massachusetts Bay", "city upon a hill"]},
        [("John Winthrop the Younger", "The son governed Connecticut and was associated with Saybrook and New London."), ("John Endecott", "The advance-settlement governor preceded the 1630 fleet and later succeeded this leader."), ("William Bradford", "Bradford governed the separate Plymouth Colony and wrote Of Plymouth Plantation."), ("Roger Williams", "Williams was the dissenter whom this leader warned before his flight.")],
        "IAC: 2024 USHB national finals, direct answerline",
        "https://www.iacompetitions.com/wp-content/uploads/2024/04/US-History-Bee-2024-Varsity-and-JV-National-Championships-Finals.pdf",
    ),
    lesson(
        "POL-031", "Warren G. Harding", "1865-1923 | Twenty-ninth president",
        "An Ohio newspaper publisher elected on a return-to-normalcy promise whose short presidency combined naval diplomacy, conservative fiscal policy, civil-rights gestures, and several defining corruption scandals.",
        [
            ("The Marion Star", "He purchased this struggling Ohio newspaper in 1884 and built it into his political base. His wife Florence Kling Harding managed its circulation and finances with far more skill than the stereotype of a ceremonial spouse suggests."),
            ("Harry Daugherty and the smoke-filled room", "Political manager Daugherty predicted he could be nominated if the 1920 Republican convention deadlocked. Party leaders settled on him during negotiations remembered as the smoke-filled-room selection."),
            ("Return to normalcy", "His 1920 phrase promised stability after World War I, Wilsonian reform, strikes, and the Red Scare. The supposedly mistaken word normalcy had appeared in English before he used it."),
            ("The front-porch campaign", "He largely campaigned from Marion while delegations visited his home. He defeated James Cox and Franklin Roosevelt in the first presidential election after nationwide woman suffrage."),
            ("The Ohio Gang", "This label covered friends and political associates who gained access to the administration. It should evoke Daugherty, Jess Smith, Charles Forbes, and Albert Fall, though not every cabinet member was corrupt."),
            ("Teapot Dome", "Interior Secretary Albert Fall secretly leased naval petroleum reserves at Teapot Dome and Elk Hills to Harry Sinclair and Edward Doheny. Fall became the first former cabinet officer imprisoned for crimes committed in office."),
            ("Charles Forbes and the Veterans Bureau", "Forbes diverted supplies and manipulated hospital contracts before fleeing to Europe. His scandal showed that the administration's corruption extended beyond petroleum leases."),
            ("Washington Naval Conference", "Secretary of State Charles Evans Hughes opened the 1921-22 conference with dramatic ship-scrapping proposals. The resulting Five-Power Treaty imposed the famous 5:5:3 capital-ship ratio."),
            ("Budget and tariff", "He signed the Budget and Accounting Act of 1921, creating the Bureau of the Budget and General Accounting Office, and the protectionist Fordney-McCumber Tariff in 1922."),
            ("Eugene Debs", "On Christmas 1921 he commuted the socialist leader's wartime Espionage Act sentence. Debs then visited the White House, making the episode an unusual reconciliation clue."),
            ("Birmingham speech", "Speaking in segregated Alabama in 1921, he endorsed political equality for Black Americans while accepting social separation. The speech angered many white Southerners but fell far short of full racial equality."),
            ("Nan Britton and Carrie Phillips", "His affairs became lasting biographical routes. Genetic testing of descendants later supported Britton's claim that he fathered Elizabeth Ann Blaesing."),
            ("Voyage of Understanding and death", "During a 1923 western trip he became the first sitting president to visit Alaska. He died at San Francisco's Palace Hotel; Florence refused an autopsy, encouraging unfounded poisoning rumors."),
        ],
        {"6": ["Washington Conference and naval limitation", "Fordney-McCumber and radio proposals", "Nan Britton"], "5": ["Return to normalcy", "Albert Fall and petroleum leases", "Eugene Debs commutation"], "4": ["Teapot Dome", "Twenty-ninth president", "death in 1923 and Coolidge succession"]},
        [("Calvin Coolidge", "The vice president succeeded after the 1923 death and later won his own term."), ("Albert Fall", "The interior secretary took bribes and controlled the oil leases."), ("Harry Daugherty", "The attorney general and political manager was investigated but never convicted in the scandals."), ("Herbert Hoover", "The capable commerce secretary belonged to the cabinet but not the corrupt Ohio Gang.")],
        "IAC: 2023 USHB national finals, direct answerline",
        "https://www.iacompetitions.com/wp-content/uploads/2024/05/US-History-Bee-2023-Varsity-and-JV-National-Championships-Finals.pdf",
    ),
    lesson(
        "POL-032", "Jefferson Davis", "1808-1889 | Confederate president",
        "A West Point officer, Mexican War hero, senator, and secretary of war who became the Confederacy's only president, was imprisoned without trial, and spent his final years defending secession.",
        [
            ("Kentucky birth and West Point", "He was born in Kentucky less than a year and roughly one hundred miles from Abraham Lincoln. At West Point he narrowly avoided punishment for his role in the 1826 Eggnog Riot."),
            ("Sarah Knox Taylor", "While serving under Zachary Taylor, he married the commander's daughter Sarah Knox. Both contracted malaria at Locust Grove, and she died only three months after the wedding."),
            ("Brierfield and Joseph Davis", "His wealthy brother Joseph established him at Brierfield plantation on Davis Bend, Mississippi. Enslaved labor supported the plantation and his return to public life."),
            ("Mississippi Rifles", "He commanded this volunteer regiment in the Mexican-American War. At Buena Vista his troops used a V-shaped formation, and he suffered a serious foot wound."),
            ("Franklin Pierce's secretary of war", "From 1853 to 1857 he enlarged and modernized the army, supported surveys for a transcontinental railroad, and oversaw the experimental Camel Corps."),
            ("Senate resignation", "He had defended slavery and states' rights but initially regarded immediate secession as strategically dangerous. He resigned from the Senate after Mississippi left the Union in January 1861."),
            ("Chosen at Montgomery", "The provisional Confederate Congress selected him president despite his preference for military command. He later won a six-year term under the Confederate Constitution."),
            ("Richmond White House", "He governed from the Confederate White House after the capital moved from Montgomery. His vice president was Alexander Stephens; major cabinet figures included Judah Benjamin and Robert Toombs."),
            ("Johnston and Bragg", "His difficult relationship with Joseph E. Johnston damaged Confederate command, while his continued confidence in Braxton Bragg generated further controversy. These names can identify his wartime leadership."),
            ("Conscription and centralization", "The Confederacy adopted national conscription, taxation, impressment, and suspension of habeas corpus. These measures exposed the tension between states' rights rhetoric and wartime central power."),
            ("Capture and the petticoat story", "Union cavalry captured him near Irwinville, Georgia, in 1865. He wore his wife's waterproof outer garment while escaping, which Northern cartoons transformed into the false claim that he disguised himself as a woman."),
            ("Fort Monroe", "He spent two years imprisoned there, initially in shackles, and was charged with treason but never tried. Horace Greeley and other prominent Northerners helped secure his bail."),
            ("Varina, Beauvoir, and his defense", "His second wife Varina Howell survived him. At Beauvoir in Mississippi he wrote The Rise and Fall of the Confederate Government, presenting secession as constitutional and minimizing slavery's centrality."),
        ],
        {"6": ["Eggnog Riot", "Sarah Knox Taylor and Brierfield", "Camel Corps and military administration"], "5": ["Petticoat capture rumor", "Pierce cabinet", "Toombs and Judah Benjamin"], "4": ["Richmond White House", "only Confederate president", "Fort Monroe imprisonment"]},
        [("Jefferson Davis", "The Confederate president; do not confuse him with Union secretary of war Jefferson Columbus Davis."), ("Alexander Stephens", "The Confederate vice president and Cornerstone Speech author."), ("Judah Benjamin", "The cabinet member who successively served as attorney general, war secretary, and secretary of state."), ("Zachary Taylor", "His first wife's father and his commander before the Mexican War.")],
        "IAC: 2018 USHB national playoff round 1, direct answerline",
        "https://www.iacompetitions.com/wp-content/uploads/2023/09/2018-HS-Nationals-US-History-Bee-Playoff-Round-1.pdf",
    ),
    lesson(
        "LAW-005", "Oliver Wendell Holmes Jr.", "1841-1935 | Supreme Court justice",
        "A wounded Civil War officer and legal theorist whose opinions shaped free-speech doctrine, judicial restraint, and American legal realism, while also including the notorious eugenics decision Buck v. Bell.",
        [
            ("The other Oliver Wendell Holmes", "His father was the physician and poet who wrote Old Ironsides. The son added Jr. and became the jurist, making profession clues essential."),
            ("Twentieth Massachusetts", "He fought with this regiment and was wounded at Ball's Bluff, Antietam, and Chancellorsville. A famous but unverified story has him shouting at Abraham Lincoln to take cover at Fort Stevens."),
            ("The Common Law, 1881", "This book opens with the idea that the life of the law has been experience rather than logic. It made him an intellectual ancestor of legal realism."),
            ("Massachusetts bench", "He served on the Massachusetts Supreme Judicial Court and became its chief justice before Theodore Roosevelt appointed him to the U.S. Supreme Court in 1902."),
            ("The Great Dissenter", "His short, forceful dissents frequently became more influential than the majorities they opposed. The nickname particularly fits his economic and free-speech opinions."),
            ("Lochner dissent", "He rejected the Court's use of liberty of contract to invalidate a bakers' hours law, writing that the Fourteenth Amendment did not enact Herbert Spencer's Social Statics."),
            ("Schenck and clear and present danger", "His unanimous 1919 opinion upheld punishment of anti-draft leaflets. The crowded-theater analogy came from this restrictive decision, not from a broad defense of speech."),
            ("Abrams dissent", "Later in 1919 he argued that truth should prevail through competition in the marketplace of ideas. Zechariah Chafee and Judge Learned Hand likely influenced his shift."),
            ("Debs and Frohwerk", "Along with Schenck, these cases formed a trilogy upholding wartime Espionage Act convictions. Do not assume every opinion associated with him protected dissenters."),
            ("Northern Securities", "He dissented when the Court broke up J. P. Morgan's railroad combination. Theodore Roosevelt regarded the vote as a personal betrayal by his appointee."),
            ("Silverthorne", "His opinion excluded illegally seized evidence and its derivatives, helping establish the principle later called fruit of the poisonous tree."),
            ("Buck v. Bell", "He wrote the 1927 majority upholding Virginia's compulsory sterilization law and declared that three generations of imbeciles were enough. This is the central dark counterweight to his civil-liberties reputation."),
            ("Retirement at ninety", "He left the Court in 1932 after nearly three decades and remains among its oldest-serving justices. He died in 1935, leaving much of his estate to the United States."),
        ],
        {"6": ["Baltzer and Zechariah Chafee", "The Common Law", "Abrams marketplace dissent"], "5": ["Herbert Spencer in Lochner", "wartime speech cases", "Great Dissenter"], "4": ["clear and present danger", "crowded-theater analogy", "Supreme Court justice"]},
        [("Oliver Wendell Holmes Sr.", "The father was a physician and poet; the son was the justice."), ("Louis Brandeis", "Brandeis wrote the major privacy dissent in Olmstead and joined later speech dissents."), ("Learned Hand", "A lower-court judge whose Masses opinion influenced free-speech thinking."), ("John Marshall Harlan", "The earlier Great Dissenter is associated with Plessy and the Civil Rights Cases.")],
        "IAC: 2018 USHB national playoff round 1, direct answerline",
        "https://www.iacompetitions.com/wp-content/uploads/2023/09/2018-HS-Nationals-US-History-Bee-Playoff-Round-1.pdf",
    ),
    lesson(
        "COL-004", "William Penn", "1644-1718 | Quaker proprietor",
        "An English Quaker writer and advocate for religious liberty whose royal land grant produced Pennsylvania, Philadelphia's planned grid, and a comparatively conciliatory early relationship with the Lenape.",
        [
            ("Admiral Sir William Penn", "His father was a prominent naval commander and creditor of Charles II. The king's grant of Pennsylvania in 1681 helped settle the Crown's debt to the father."),
            ("Thomas Loe and George Fox", "Quaker missionary Thomas Loe influenced him in Ireland, and he became a follower of movement founder George Fox. His conversion brought expulsion, imprisonment, and conflict with his family."),
            ("No Cross, No Crown", "This 1669 prison treatise defended Quaker spirituality and plain conduct, including refusal of flattering titles and insistence on addressing individuals as thou."),
            ("Penn and Mead trial", "A London jury refused to convict him and William Mead for unlawful preaching. The punishment of the jurors produced Bushel's Case, a landmark for jury independence."),
            ("The Great Case of Liberty of Conscience", "This tract argued that coercion in religion violated both Christianity and natural rights. Religious toleration was foundational to his colonial plan."),
            ("Pennsylvania, 1681", "He preferred New Wales or Sylvania, but Charles II named the province Pennsylvania in honor of the admiral. The proprietor feared observers would think he had named it for himself."),
            ("The Holy Experiment", "The colony was intended to demonstrate representative government, toleration, and Quaker principles while also generating income for its proprietor."),
            ("Frame and Charter", "The 1682 Frame of Government established an elected assembly and complex councils. The 1701 Charter of Privileges strengthened the assembly and provided broad religious liberty for monotheists."),
            ("Philadelphia and Thomas Holme", "Surveyor Thomas Holme translated the proprietor's plan into a grid between the Delaware and Schuylkill. Major streets were named for trees, and public squares punctuated the plan."),
            ("Tamanend and Shackamaxon", "Tradition associates him with a peace agreement beneath an elm at Shackamaxon with Lenape leader Tamanend. No surviving written treaty proves the celebrated scene."),
            ("Walking Purchase correction", "The fraudulent 1737 Walking Purchase occurred nineteen years after his death and was arranged by his sons and colonial officials. It should identify Pennsylvania's later proprietors, not an agreement personally made by him."),
            ("Pennsbury and two visits", "He resided at Pennsbury Manor during visits from 1682 to 1684 and 1699 to 1701. Most of his proprietary administration occurred from England."),
            ("Debt, stroke, and death", "Fraud by agent Philip Ford helped place him in debtors' prison. Strokes beginning in 1712 incapacitated him, and he died at Ruscombe in 1718."),
        ],
        {"6": ["Thomas Loe and Philip Ford", "Penn and Mead jury trial", "No Cross, No Crown"], "5": ["Charter of Privileges", "Thomas Holme and tree streets", "Tamanend and Shackamaxon"], "4": ["Quaker proprietor", "Philadelphia", "namesake colony on the Delaware"]},
        [("Admiral William Penn", "The father was the naval commander whose unpaid royal debt helped produce the grant."), ("Thomas Penn", "The son participated in the later Walking Purchase."), ("George Fox", "Fox founded the Quaker movement; this proprietor became its politically connected defender."), ("Roger Williams", "Williams founded Rhode Island around liberty of conscience but was not a Quaker proprietor.")],
        "IAC: 2021 USHB national semifinal route and repeated direct preliminaries",
        "https://www.iacompetitions.com/wp-content/uploads/2023/09/2020-2021-HS-US-History-Bee-Semifinals-B-Set.pdf",
    ),
    lesson(
        "POL-033", "Thomas Jefferson", "1743-1826 | Third president",
        "A Virginia planter, revolutionary writer, diplomat, party founder, president, architect, and university builder whose language of liberty coexisted with slaveholding and the exploitation of the Hemings family.",
        [
            ("Shadwell, William and Mary, George Wythe", "Born at Shadwell, he studied at the College of William and Mary and read law under George Wythe. Wythe linked him to Virginia's legal and classical intellectual tradition."),
            ("A Summary View, 1774", "This pamphlet argued that colonists possessed rights independent of Parliament and addressed George III as the empire's chief officer. It established his reputation before independence."),
            ("Declaration draft", "The Committee of Five assigned him the first draft. Congress removed his long attack on the slave trade and revised other language before adopting the document."),
            ("Virginia governor and Arnold's raid", "While governor, he fled Richmond as Benedict Arnold's British force approached in 1781. Critics later used the episode to question his wartime leadership."),
            ("Notes on the State of Virginia", "Organized as responses to Francois Barbe-Marbois, this book covers geography, government, and natural history while exposing his racist assumptions and anxieties about slavery."),
            ("Paris, Maria Cosway, and the Hemingses", "As minister to France he wrote the Head and Heart dialogue to Maria Cosway. Sally Hemings accompanied his household, and strong historical and genetic evidence identifies him as father of her children."),
            ("Hamilton's rival", "As Washington's secretary of state he opposed assumption, the national bank, and a pro-British foreign policy. His alliance with James Madison created the Democratic-Republican opposition."),
            ("Kentucky Resolutions", "After the Alien and Sedition Acts, he secretly drafted Kentucky's resolutions while Madison wrote Virginia's. Their compact reasoning later fed nullification arguments."),
            ("Revolution of 1800", "The electoral tie with Aaron Burr sent the election to the House, where Hamilton preferred him. The crisis produced the Twelfth Amendment's separate presidential and vice-presidential ballots."),
            ("Barbary War", "He rejected continuing tribute to Tripoli and sent naval forces to the Mediterranean. The conflict included the burning of the captured Philadelphia and the march to Derna."),
            ("Louisiana and Lewis and Clark", "He purchased Louisiana despite doubts that the Constitution authorized acquiring territory. Meriwether Lewis and William Clark then explored the trans-Mississippi West."),
            ("Embargo", "The 1807 ban on American overseas commerce attempted peaceful coercion after British and French violations. Smuggling and economic pain made it one of his presidency's greatest failures."),
            ("Monticello, the university, and July Fourth", "He designed Monticello and the University of Virginia's Academical Village and wanted both achievements, plus religious freedom, on his tomb. He died on July 4, 1826, the same day as John Adams."),
        ],
        {"6": ["Gregoire and Banneker letters", "Head and Heart to Maria Cosway", "final Jubilee letter"], "5": ["Danbury Baptists and wall of separation", "Kentucky Resolutions", "Notes on Virginia"], "4": ["Declaration of Independence", "Louisiana Purchase", "third president"]},
        [("Thomas Jefferson", "The president and Declaration drafter; do not confuse him with Confederate president Jefferson Davis."), ("James Madison", "Madison wrote the Virginia Resolutions and shared party leadership but drafted the Constitution, not the Declaration."), ("George Wythe", "The mentor and first American law professor."), ("Benjamin Banneker", "The Black surveyor and almanac author who challenged this founder's racial assumptions.")],
        "IAC: 2019 National History Bowl national playoff round 5, direct answerline",
        "https://www.iacompetitions.com/wp-content/uploads/2023/08/2019-HS-Nationals-History-Bowl-Playoff-Round-5.pdf",
    ),
    lesson(
        "POL-034", "William Howard Taft", "1857-1930 | President and chief justice",
        "A judge and colonial administrator who succeeded Theodore Roosevelt, fractured the Republican Party, and later achieved his preferred office as the only former president to serve as chief justice.",
        [
            ("Alphonso Taft and Cincinnati", "His father served as attorney general and secretary of war under Grant. The younger man built his early career through Ohio judgeships rather than through electoral campaigning."),
            ("Solicitor general and circuit judge", "Benjamin Harrison appointed him solicitor general in 1890 and then to the Sixth Circuit. He repeatedly preferred judicial work to partisan politics."),
            ("Philippine Commission", "McKinley sent him to organize civil government, and in 1901 he became the first civilian governor-general of the Philippines. His paternal language about little brown brothers reflected imperial assumptions."),
            ("The Vatican mission", "He negotiated with Pope Leo XIII over purchasing friar lands in the Philippines. The mission made church property and colonial administration useful early clues."),
            ("Secretary of war and Cuba", "He succeeded Elihu Root in Roosevelt's cabinet, supervised Philippine and canal matters, and briefly served as provisional governor of Cuba after Tomas Estrada Palma's government collapsed."),
            ("Roosevelt's chosen successor", "Roosevelt promoted him for the 1908 Republican nomination. Their friendship broke when progressives concluded that the new administration had betrayed Roosevelt's program."),
            ("Dollar Diplomacy", "Secretary of State Philander Knox encouraged American investment to extend influence, especially in Latin America and China. Intervention in Nicaragua became a defining example."),
            ("Payne-Aldrich", "He praised this tariff as the best Republicans had passed, alienating insurgent progressives who expected deeper reductions. The dispute helped split the party."),
            ("Ballinger-Pinchot", "He supported Interior Secretary Richard Ballinger and dismissed conservationist Gifford Pinchot after Pinchot publicly attacked Ballinger. The controversy accelerated Roosevelt's break with him."),
            ("More antitrust cases", "His administration filed more antitrust suits than Roosevelt's, including actions against Standard Oil and American Tobacco. Yet Roosevelt criticized its case against U.S. Steel."),
            ("The election of 1912", "Roosevelt's Progressive Party split Republican voters. The incumbent finished third behind Woodrow Wilson and Roosevelt, carrying only Utah and Vermont."),
            ("Chief justice, 1921", "Harding appointed him to succeed Edward Douglass White. He remains the only person to have headed both the executive branch and the Supreme Court."),
            ("Judges' Bill and Supreme Court building", "He championed the Judiciary Act of 1925, which expanded discretionary certiorari, and pressed for a separate Supreme Court building. He died before the building opened."),
        ],
        {"6": ["Provisional governor after Estrada Palma", "Vatican friar-land mission", "Benjamin Harrison solicitor general"], "5": ["Philippine civil governor", "Elihu Root succession", "McReynolds, Holmes, Brandeis, and Van Devanter bench"], "4": ["Twenty-seventh president", "chief justice", "only person to lead presidency and Court"]},
        [("Theodore Roosevelt", "The predecessor and former ally who ran as a Progressive in 1912."), ("Charles Evans Hughes", "A later chief justice and 1916 nominee, not a president."), ("Edward Douglass White", "The chief justice whom this former president succeeded in 1921."), ("Robert Taft", "His son became the conservative Ohio senator known as Mr. Republican.")],
        "IAC: 2019 National History Bowl national playoff round 1, direct answerline",
        "https://www.iacompetitions.com/wp-content/uploads/2023/08/2019-HS-Nationals-History-Bowl-Playoff-Round-1.pdf",
    ),
    lesson(
        "POL-035", "Alexander Hamilton", "c. 1755-1804 | Treasury founder",
        "A Caribbean-born revolutionary officer, constitutional polemicist, and first treasury secretary who built the federal financial system, led the early Federalists, and died after a duel with Aaron Burr.",
        [
            ("Nevis, St. Croix, and the hurricane letter", "Born out of wedlock in the Caribbean, he clerked for Beekman and Cruger on St. Croix. A vivid 1772 hurricane account helped patrons send him to mainland North America for education."),
            ("King's College and the Hearts of Oak", "He studied at the future Columbia University and joined a New York militia company. As an artillery officer he fought at Trenton and Princeton."),
            ("Washington's aide and Laurens", "He became Washington's principal aide-de-camp, managing correspondence and intelligence. His intense friendship with John Laurens and frustration with staff work are frequent biographical routes."),
            ("Yorktown Redoubt Ten", "After demanding a field command, he led the nighttime bayonet assault on British Redoubt Number Ten. French troops simultaneously captured Number Nine."),
            ("Eliza Schuyler", "His marriage joined him to Philip Schuyler's powerful New York family. Eliza later preserved his papers and helped establish the Orphan Asylum Society."),
            ("Seabury pamphlet battle", "He answered loyalist Samuel Seabury's Letters of a Westchester Farmer with A Full Vindication and The Farmer Refuted. These youthful writings opened IAC's 2018 playoff question."),
            ("Constitution and Publius", "At Philadelphia he advocated an extremely strong executive and Senate. He then wrote most of the Federalist essays alongside James Madison and John Jay."),
            ("Public credit and assumption", "As treasury secretary he proposed funding federal securities at face value and assuming state Revolutionary debts. The measures tied creditors to the new government."),
            ("The dinner-table compromise", "Jefferson hosted the meeting at which Madison accepted assumption while northern leaders accepted a permanent Potomac capital. This became the Compromise of 1790."),
            ("Bank and implied powers", "His defense of the First Bank argued that necessary means could be implied from enumerated powers. Washington accepted his reasoning over Jefferson's strict construction."),
            ("Manufactures, customs, and cutters", "His Report on Manufactures promoted industrial development, while his department created customs administration and the Revenue Cutter Service, an ancestor of the Coast Guard."),
            ("Reynolds Pamphlet", "To rebut corruption charges involving James Reynolds, he publicly admitted an affair with Maria Reynolds. The confession protected his financial reputation while destroying his family and political standing."),
            ("Adams, Burr, and Weehawken", "He attacked John Adams in a private pamphlet that became public, then helped Jefferson defeat Burr in 1801. Burr fatally wounded him in an 1804 duel at Weehawken."),
        ],
        {"6": ["grave and phlegmatic pamphlet voice", "Letters of a Westchester Farmer", "A Full Vindication"], "5": ["Samuel Seabury and The Farmer Refuted", "Tench Coxe and Paterson", "Revenue Cutter and reports"], "4": ["Federalist Papers", "first treasury secretary", "national bank and public credit"]},
        [("Alexander Hamilton", "The treasury secretary; do not confuse him with later vice president Alexander Hamilton Stephens."), ("James Madison", "The Federalist coauthor who later opposed the financial program."), ("Philip Schuyler", "His father-in-law, senator, and New York political ally."), ("Aaron Burr", "The electoral rival and duelist who killed him.")],
        "IAC: 2018 USHB national playoff round 1, direct answerline",
        "https://www.iacompetitions.com/wp-content/uploads/2023/09/2018-HS-Nationals-US-History-Bee-Playoff-Round-1.pdf",
    ),
]

LESSONS += [
    lesson(
        "MISC-050", "Horace Greeley", "1811-1872 | Editor and presidential candidate",
        "A reform-minded newspaper editor who built the New-York Tribune, promoted western settlement and antislavery politics, pressed Lincoln toward emancipation, and died after losing the 1872 election.",
        [
            ("Printer from New Hampshire", "Born in Amherst, New Hampshire, he apprenticed at the Northern Spectator in East Poultney, Vermont. His distinctive appearance and intense work habits became part of his public persona."),
            ("Log Cabin and the Tribune", "He edited a campaign paper supporting William Henry Harrison in 1840, then founded the New-York Tribune in 1841 with Thomas McElrath."),
            ("Margaret Fuller and Whitelaw Reid", "Fuller became the Tribune's literary editor and one of its most important critics. Whitelaw Reid later managed the paper and became a national Republican figure."),
            ("Associationism", "He gave Albert Brisbane space to promote Charles Fourier's cooperative social system. The connection links him to Brook Farm and other antebellum utopian experiments."),
            ("Labor and homesteads", "He supported workers' organization, land reform, and cheap western farms. His newspaper helped normalize policies that culminated in the Homestead Act."),
            ("Go West correction", "He popularized Go West, young man, but probably did not coin it. The phrase is often credited to John B. L. Soule, whose exact priority remains disputed."),
            ("Seward-Weed-Greeley firm", "He initially cooperated with William Seward and Thurlow Weed in New York Whig politics. A bitter 1854 letter announced the dissolution of their political partnership."),
            ("Spitting on the 1852 platform", "He wrote that he defied, execrated, and spat upon the Whig platform supporting the Compromise of 1850. The quotation appeared in IAC's national playoff route."),
            ("A brief House term", "After David S. Jackson lost his seat for election fraud, this editor served the final months of the term in 1848-49. He used the position to attack congressional mileage abuses."),
            ("Prayer of Twenty Millions", "His 1862 open letter demanded stronger enforcement of emancipation policy. Lincoln replied that his paramount object was to save the Union, then issued the preliminary proclamation weeks later."),
            ("Niagara peace mission", "In 1864 he pursued an unauthorized meeting with Confederate representatives in Canada. Lincoln converted the episode into a demand for reunion and abandonment of slavery."),
            ("Jefferson Davis bail", "He signed the former Confederate president's 1867 bail bond with other prominent men. Many longtime readers and Union supporters denounced him for the gesture."),
            ("Liberal Republican defeat", "In 1872 he ran against Grant with B. Gratz Brown and Democratic endorsement. After his wife died and he suffered a breakdown, he died before electoral votes were counted; votes cast for him were rejected."),
        ],
        {"6": ["David S. Jackson special election", "1852 platform denunciation", "Georgia electoral votes rejected"], "5": ["Whitelaw Reid and Margaret Fuller", "Prayer of Twenty Millions", "Liberal Republican candidacy"], "4": ["New-York Tribune", "Go West, young man", "death after losing in 1872"]},
        [("Thurlow Weed", "The party organizer and former ally who managed Seward's political network."), ("William Lloyd Garrison", "The abolitionist editor of the Liberator, more uncompromising on immediate abolition."), ("Whitelaw Reid", "The Tribune lieutenant who later became an ambassador and vice-presidential nominee."), ("Charles A. Dana", "Another Tribune editor who later worked in the War Department and ran the New York Sun.")],
        "IAC: 2018 National History Bowl national playoff round 1, direct answerline",
        "https://www.iacompetitions.com/wp-content/uploads/2023/08/2018-HS-Nationals-History-Bowl-Playoff-Round-1.pdf",
    ),
    lesson(
        "POL-036", "Richard Nixon", "1913-1994 | Thirty-seventh president",
        "A California Quaker who rose through anti-communist investigations, lost narrowly in 1960, returned to win twice, transformed Cold War diplomacy, and resigned over Watergate.",
        [
            ("Yorba Linda and Duke Law", "He grew up in a financially strained Quaker family that operated a grocery and service station in Whittier. A scholarship took him to Duke Law School."),
            ("Voorhis and the Pink Lady", "He defeated congressman Jerry Voorhis in 1946 by stressing communist-linked support, then attacked Helen Gahagan Douglas as the Pink Lady in the 1950 Senate race."),
            ("Alger Hiss and the Pumpkin Papers", "As a House Un-American Activities Committee member, he championed Whittaker Chambers's allegations against Hiss. Microfilm hidden in a hollowed pumpkin became the investigation's famous physical clue."),
            ("Checkers speech", "Accused in 1952 of benefiting from a private political fund, he defended his finances on television and said his daughters would keep a gifted dog named Checkers. Eisenhower retained him on the ticket."),
            ("Kitchen Debate", "As vice president he debated Nikita Khrushchev inside an American model kitchen at the 1959 Moscow exhibition, turning consumer goods into Cold War propaganda."),
            ("The 1960 debates", "A knee injury, infection, and poor television appearance hurt him against John Kennedy. Radio listeners were sometimes said to prefer him, though evidence for that famous claim is weak."),
            ("Last press conference", "After losing the 1962 California governor's race to Pat Brown, he told reporters they would not have him to kick around anymore. The apparent farewell made his 1968 comeback more dramatic."),
            ("Southern strategy and Agnew", "His 1968 campaign appealed to voters alienated by civil-rights unrest and Democratic change. He chose Maryland governor Spiro Agnew as his running mate."),
            ("China opening", "Secret diplomacy by Henry Kissinger prepared his 1972 visit to Mao Zedong and Zhou Enlai. The Shanghai Communique acknowledged competing positions over Taiwan."),
            ("Detente and SALT", "He met Leonid Brezhnev and signed the Anti-Ballistic Missile Treaty and interim SALT I agreement. Triangular diplomacy used relations with China to pressure the Soviet Union."),
            ("Vietnamization and Cambodia", "He withdrew U.S. ground forces while expanding South Vietnamese responsibility, but bombing and incursions spread the war into Cambodia. The Paris Peace Accords followed in 1973."),
            ("Domestic surprises", "His administration created the Environmental Protection Agency, signed OSHA and major environmental laws, imposed wage-price controls, and ended dollar convertibility into gold in the Nixon Shock."),
            ("Watergate and resignation", "The break-in, cover-up, White House tapes, Saturday Night Massacre, and United States v. Nixon destroyed his presidency. He resigned on August 9, 1974, and Gerald Ford later pardoned him."),
        ],
        {"6": ["Nixon Agonistes and carpet-beating scene", "Six Crises", "Imperial Presidency"], "5": ["The Final Days", "Woodward and Bernstein", "televised debate details"], "4": ["Watergate", "thirty-seventh president", "resignation and Ford pardon"]},
        [("Richard Nixon", "The president; Pat Nixon was his wife and a separate first-lady answerline possibility."), ("Alger Hiss", "The accused diplomat whose case launched this politician nationally."), ("Henry Kissinger", "The national security adviser and secretary of state who directed much of the diplomacy."), ("Spiro Agnew", "The vice president who resigned over Maryland bribery unrelated to Watergate.")],
        "IAC: 2019 USHB national playoff round 2, direct answerline",
        "https://www.iacompetitions.com/wp-content/uploads/2023/09/2019-HS-Nationals-US-History-Bee-Playoff-Round-2.pdf",
    ),
    lesson(
        "REF-026", "John Brown", "1800-1859 | Militant abolitionist",
        "A deeply religious abolitionist whose violent campaign in Bleeding Kansas and failed seizure of Harpers Ferry transformed him into either a terrorist or martyr on the eve of the Civil War.",
        [
            ("Owen Brown and the enslaved boy", "His Calvinist father Owen opposed slavery. The younger man later recalled that seeing an enslaved boy beaten helped turn moral opposition into a personal calling."),
            ("Commercial failures", "He tried tanning, land speculation, sheep breeding, and wool brokerage, often failing and accumulating debts. In Springfield he worked with Simon Perkins and encountered a strong Black abolitionist community."),
            ("League of Gileadites", "He organized this group to resist enforcement of the Fugitive Slave Act. Its biblical name and practical rescue plans are excellent early clues."),
            ("North Elba", "Gerrit Smith offered Adirondack land to Black settlers, and this abolitionist moved his family there. He was eventually buried at the North Elba farm."),
            ("Pottawatomie", "After the sack of Lawrence and caning of Charles Sumner, his party killed five proslavery men along Pottawatomie Creek in May 1856. He directed but may not have personally struck the victims."),
            ("Black Jack and Henry Clay Pate", "His force captured proslavery commander Pate at this 1856 clash. A prisoner exchange helped recover two of his sons."),
            ("Osawatomie", "He fought a larger proslavery force near this Kansas settlement, producing the nickname Osawatomie attached to him. A later progressive magazine adopted the same name."),
            ("The Secret Six", "Thomas Wentworth Higginson, Theodore Parker, Samuel Gridley Howe, Franklin Sanborn, George Luther Stearns, and Gerrit Smith supplied varying degrees of support for his plans."),
            ("Chatham Convention", "At Chatham, Canada West, in 1858, his supporters adopted a provisional constitution for a revolutionary antislavery government. Black activist Martin Delany participated."),
            ("Harpers Ferry", "In October 1859 he seized the federal armory hoping enslaved people would join an expanding liberation movement. He took Lewis Washington hostage but became trapped in the engine house."),
            ("Kagi, Newby, Oliver, and Watson", "John Henry Kagi and Dangerfield Newby died in the raid, as did his sons Oliver and Watson. Remembering the small raider network distinguishes deep clues from the generic event."),
            ("Lee, Stuart, and Israel Greene", "Colonel Robert E. Lee commanded the response, J. E. B. Stuart delivered the surrender demand, and Marine lieutenant Israel Greene helped storm the engine house."),
            ("Trial, final note, and martyrdom", "Virginia convicted him of treason, murder, and inciting slave revolt. Before his December 2 execution he predicted that slavery's crimes would be purged only with blood."),
        ],
        {"6": ["Silas Soule and Whitman poem", "Kagi, Newby, Oliver, and Watson", "Secret Six and Victor Hugo"], "5": ["Pottawatomie", "Battle of Black Jack", "Chatham constitution"], "4": ["Harpers Ferry armory", "militant abolitionist", "execution in 1859"]},
        [("John Brown", "The abolitionist; do not confuse him with the song John Brown's Body."), ("John Brown's Body", "The marching song later inspired Julia Ward Howe's Battle Hymn of the Republic."), ("Nat Turner", "Turner led an enslaved uprising in Virginia in 1831 rather than a white abolitionist raid in 1859."), ("Denmark Vesey", "Vesey was accused of planning an 1822 Charleston uprising.")],
        "IAC: 2021 USHB national semifinal route and repeated direct preliminaries",
        "https://www.iacompetitions.com/wp-content/uploads/2023/09/2020-2021-HS-US-History-Bee-Semifinals-B-Set.pdf",
    ),
    lesson(
        "POL-037", "Charles Evans Hughes", "1862-1948 | Governor, nominee, diplomat, chief justice",
        "A reform governor and almost-president who served twice on the Supreme Court, ran against Wilson in 1916, organized naval diplomacy, and presided over the constitutional revolution of 1937.",
        [
            ("Baptist household and law", "Born in Glens Falls, New York, to a Baptist minister, he graduated from Brown and Columbia Law. His intense preparation and beard became recognizable public traits."),
            ("Armstrong investigation", "His questioning in the 1905 New York legislative investigation exposed insurance-company abuses involving campaign contributions and self-dealing. The performance launched him into electoral politics."),
            ("Governor of New York", "Elected in 1906, he strengthened public-service regulation, fought racetrack gambling, and resisted Republican machine control. Theodore Roosevelt supported him despite policy tensions."),
            ("First Supreme Court service", "William Howard Taft appointed him associate justice in 1910. He resigned in 1916 to accept the Republican presidential nomination."),
            ("The 1916 near victory", "He lost to Woodrow Wilson by only twenty-three electoral votes. A famous story blamed his failure to greet California governor Hiram Johnson, though the defeat had broader causes."),
            ("Secretary of state", "Under Harding and Coolidge he defended an internationalist foreign policy without joining the League of Nations. He pursued arbitration, debt diplomacy, and the Open Door in China."),
            ("Washington Naval Conference", "He opened the 1921 conference by proposing large-scale scrapping of capital ships. His proposal led into the Four-Power, Five-Power, and Nine-Power treaties."),
            ("World Court and private practice", "He advocated U.S. participation in the Permanent Court of International Justice and later returned to elite legal practice before becoming chief justice."),
            ("Chief justice after Taft", "Herbert Hoover appointed him in 1930. His son, Charles Evans Hughes Jr., resigned as solicitor general to avoid arguing before his father's Court."),
            ("Near v. Minnesota", "He wrote the 1931 majority applying freedom of the press against state prior restraints. This liberal ruling complicates any simple description of him as conservative."),
            ("Schechter Poultry", "His unanimous opinion invalidated the National Industrial Recovery Act's code system for excessive delegation and effects outside interstate commerce."),
            ("Four Horsemen and Three Musketeers", "He and Owen Roberts occupied the Court's center between conservative and liberal blocs. Their votes became decisive in New Deal constitutional cases."),
            ("Court-packing and the 1937 shift", "He rebutted Roosevelt's claim that the Court was behind on work in a letter to Burton Wheeler. He then led majorities sustaining labor and Social Security laws after the constitutional shift."),
        ],
        {"6": ["son's solicitor-general resignation", "Near v. Minnesota", "insurance investigation"], "5": ["Schechter Poultry", "Hughes and Roberts between Court blocs", "Washington Conference"], "4": ["1916 nominee", "Harding secretary of state", "chief justice through the 1930s"]},
        [("Charles Evans Hughes Jr.", "The son was solicitor general and resigned when his father became chief justice."), ("Owen Roberts", "The swing justice associated with the switch in time, not the chief justice."), ("William Howard Taft", "The former president and chief justice whom this jurist succeeded."), ("Harlan Fiske Stone", "The justice who succeeded him as chief justice in 1941.")],
        "IAC: 2019 USHB national playoff round 2, direct answerline",
        "https://www.iacompetitions.com/wp-content/uploads/2023/09/2019-HS-Nationals-US-History-Bee-Playoff-Round-2.pdf",
    ),
    lesson(
        "POL-038", "John Quincy Adams", "1767-1848 | Diplomat, president, congressman",
        "The extraordinarily experienced diplomat who became sixth president through the disputed election of 1824, then built a more consequential post-presidential career fighting slavery in the House.",
        [
            ("Bunker Hill from Penn's Hill", "As a child he watched smoke from the Battle of Bunker Hill with his mother Abigail. His childhood letters reveal the pressure of growing up in a revolutionary political family."),
            ("Francis Dana and Russia", "As a teenager he served as secretary and interpreter for diplomat Francis Dana's mission to Catherine the Great's Russia. He later studied at Leiden and graduated from Harvard."),
            ("Louisa Catherine Johnson", "He married the London-born daughter of an American merchant while serving abroad. She remains the only first lady born outside the United States or its colonies."),
            ("Federalist senator who broke ranks", "He supported Jefferson's Louisiana Purchase and embargo despite Federalist opposition. The break ended his Massachusetts Senate career but helped Madison appoint him minister to Russia."),
            ("Minister during Napoleon's invasion", "He was in St. Petersburg when Napoleon invaded Russia in 1812 and developed a productive relationship with Tsar Alexander I."),
            ("Treaty of Ghent", "He joined Henry Clay, Albert Gallatin, James Bayard, and Jonathan Russell in negotiating the treaty ending the War of 1812."),
            ("Monroe's secretary of state", "He negotiated the Adams-Onis Treaty, helped formulate the Monroe Doctrine, and supported the Convention of 1818 and Rush-Bagot limitations with Britain."),
            ("The corrupt bargain", "After no candidate won an electoral majority in 1824, the House selected him over Andrew Jackson. His appointment of Henry Clay as secretary of state generated the enduring accusation."),
            ("Lighthouses of the skies", "His ambitious national program included roads, canals, scientific exploration, a national university, and an astronomical observatory. Opponents mocked the observatory phrase."),
            ("The pool table", "Jacksonians portrayed his purchase of a billiard table with personal funds as aristocratic extravagance. The minor controversy illustrates the relentless opposition to his presidency."),
            ("Old Man Eloquent", "Returning to the House in 1831, he fought the gag rule that automatically tabled antislavery petitions. Congress finally repealed it in 1844."),
            ("The Amistad argument", "He argued before the Supreme Court for the freedom of the African captives in 1841. His lengthy presentation invoked natural rights and the Declaration."),
            ("Smithsonian and final collapse", "He helped direct James Smithson's bequest toward a national scientific institution. In 1848 he collapsed in the House after opposing honors for Mexican War officers and died in the Speaker's Room."),
        ],
        {"6": ["acutest enemy of slavery quotation", "collapse over Mexican War honors", "James Smithson's bequest"], "5": ["first minister to Russia", "post-presidential House career", "Amistad argument"], "4": ["corrupt bargain with Clay", "sixth president", "son of the second president"]},
        [("John Adams", "The father was the second president and never returned to Congress afterward."), ("John Quincy Adams", "The son was the sixth president, diplomat, and antislavery representative."), ("Henry Clay", "The House speaker who backed him in 1824 and became secretary of state."), ("Andrew Jackson", "The 1824 plurality winner who defeated him in the bitter 1828 rematch.")],
        "IAC: 2015 National History Bee finals, direct answerline",
        "https://www.iacompetitions.com/wp-content/uploads/2023/08/2015-HS-Nationals-History-Bee-Finals.pdf",
    ),
    lesson(
        "POL-039", "James K. Polk", "1795-1849 | Eleventh president",
        "A Tennessee Jacksonian and surprise 1844 nominee who achieved nearly every stated policy goal by cutting tariffs, restoring an independent treasury, settling Oregon, and acquiring the Mexican Cession.",
        [
            ("McDowell's surgery", "As a teenager he underwent dangerous surgery for urinary stones by pioneering Kentucky surgeon Ephraim McDowell, without modern anesthesia or antisepsis. The operation may have left him infertile."),
            ("University of North Carolina", "He graduated in 1818, studied law under Felix Grundy, and entered Tennessee politics as an ally of Andrew Jackson."),
            ("Young Hickory", "This nickname advertised him as Jackson's disciplined protege. Unlike Jackson, he was an exacting administrator who closely supervised cabinet departments."),
            ("Speaker of the House", "He served from 1835 to 1839 and remains the only House speaker to become president. He defended Jacksonian policies during the Bank and slavery-petition conflicts."),
            ("Tennessee defeats", "After one gubernatorial victory, he lost reelection to James C. Jones and lost again in 1843. Those defeats made his sudden national nomination more surprising."),
            ("The first dark horse", "At the 1844 Democratic convention, Martin Van Buren's resistance to immediate Texas annexation blocked him. The convention turned to this compromise candidate on the ninth ballot."),
            ("Who is James K. Polk?", "Whigs used the question to mock his obscurity. He ran with George M. Dallas against Henry Clay while linking Texas annexation to claims in Oregon."),
            ("Four major goals", "He sought a lower tariff, restoration of the independent treasury, settlement of the Oregon boundary, and acquisition of California. By one term's end he had achieved all four."),
            ("Oregon and forty-nine", "Campaign expansionists demanded all territory to latitude 54 degrees 40 minutes, but the 1846 Oregon Treaty compromised with Britain largely along the forty-ninth parallel."),
            ("Slidell and the disputed border", "After Mexico rejected envoy John Slidell's purchase offer, he ordered Zachary Taylor into territory between the Nueces and Rio Grande claimed by both countries."),
            ("Thornton and the Spot Resolutions", "The Thornton clash allowed him to claim that American blood had been shed on American soil. Abraham Lincoln demanded the exact spot, challenging the war's justification."),
            ("Trist and Guadalupe Hidalgo", "He recalled diplomat Nicholas Trist, but Trist ignored the order and completed the 1848 treaty. Mexico ceded vast western territory for fifteen million dollars."),
            ("One term and 103 days", "He honored his pledge not to seek reelection and died of cholera only 103 days after leaving office, the shortest retirement of any president."),
        ],
        {"6": ["Dixon Lewis and treasury policy", "river-and-harbor veto", "McDowell surgery"], "5": ["Spot Resolutions", "dark-horse ninth ballot", "Walker Tariff and Independent Treasury"], "4": ["Mexican-American War", "Oregon settlement", "eleventh president"]},
        [("James K. Polk", "The expansionist president; Leonidas Polk was his distant cousin and a Confederate bishop-general."), ("Zachary Taylor", "The general sent to the Rio Grande who later became president."), ("Nicholas Trist", "The diplomat who completed the peace treaty despite being recalled."), ("George M. Dallas", "The vice president and 1844 running mate.")],
        "IAC: 2017 National History Bowl national playoff round 1, direct answerline",
        "https://www.iacompetitions.com/wp-content/uploads/2023/08/2017-HS-Nationals-History-Bowl-Playoff-Round-1.pdf",
    ),
    lesson(
        "REL-012", "Anne Hutchinson", "1591-1643 | Puritan dissenter",
        "A skilled midwife and religious teacher whose challenge to Massachusetts ministers produced the Antinomian Controversy, banishment to Rhode Island, and death during Kieft's War in New Netherland.",
        [
            ("Francis Marbury", "Her father was an English clergyman repeatedly punished for criticizing poorly educated bishops and ministers. His defiance supplied a family model for challenging religious authority."),
            ("John Cotton and Boston", "She followed minister John Cotton to Massachusetts in 1634. Her household's status and her work as a midwife gave her unusual access across the community."),
            ("Meetings for women and men", "She began by discussing sermons with women, then attracted mixed gatherings that could include dozens of listeners. Authorities feared an alternative center of religious influence."),
            ("Covenant of grace", "She emphasized salvation through God's freely given grace and accused most colony ministers of preaching a covenant of works. Cotton was the principal minister she exempted."),
            ("Henry Vane", "The young governor supported the grace faction, while John Winthrop and Thomas Dudley opposed it. Vane lost political control and returned to England."),
            ("John Wheelwright", "Her brother-in-law's fast-day sermon attacked the opposing ministers. His conviction for sedition turned theological disagreement into a political crisis."),
            ("Antinomian or Free Grace Controversy", "Opponents called her followers antinomians, implying that inward grace freed them from moral law. Supporters preferred free grace and rejected the accusation."),
            ("The 1637 civil trial", "At Newtown she answered Winthrop and Dudley skillfully until claiming direct revelation from God. That claim gave magistrates grounds to convict and banish her."),
            ("Church trial and John Cotton's break", "At the 1638 church proceeding, Cotton withdrew support and the Boston congregation excommunicated her. Civil banishment and church excommunication were separate actions."),
            ("Portsmouth and the Aquidneck Compact", "William Coddington, her husband William, and other supporters founded Pocasset, later Portsmouth, on Aquidneck Island. The settlement joined Rhode Island."),
            ("Mary Dyer and the monstrous births", "She helped conceal Mary Dyer's severely malformed stillbirth, and later suffered an abnormal pregnancy herself. Winthrop publicized both as supposed divine judgments."),
            ("Pelham Bay and the Siwanoy", "After her husband died, she moved beyond Massachusetts authority into New Netherland. Siwanoy warriors killed her and most of her household in 1643 during Kieft's War; daughter Susanna survived."),
            ("Wampage and place names", "Tradition says Siwanoy leader Wampage took a name associated with her after the attack. The Hutchinson River and parkway preserve her surname near the death site."),
        ],
        {"6": ["Wampage naming tradition", "Thomas Dudley and John Cotton theology", "Mary Dyer's concealed stillbirth"], "5": ["covenant of grace", "Antinomian trial", "Henry Vane and Wheelwright"], "4": ["Portsmouth", "Rhode Island exile", "banished from Massachusetts Bay"]},
        [("Anne Hutchinson", "The lay teacher banished during the Antinomian Controversy."), ("Mary Dyer", "The follower who became a Quaker and was executed in Boston in 1660."), ("Roger Williams", "The minister banished earlier over church-state and Indigenous-land issues."), ("John Cotton", "The minister whose grace theology inspired her before he withdrew support.")],
        "IAC: 2020 National History Bee national semifinals, direct answerline",
        "https://www.iacompetitions.com/wp-content/uploads/2023/08/2020-HS-Nationals-History-Bee-Semifinals.pdf",
    ),
]
