"""Compact six-to-ten-minute lessons prepared for September 1, 2026."""


def lesson(identifier, title, era, orientation, associations, route, locks, source_label, source_url):
    return {
        "id": identifier,
        "format": "compact-association-v1",
        "title": title,
        "era": era,
        "orientation": orientation,
        "associations": [{"label": label, "text": text} for label, text in associations],
        "iacRoute": route,
        "confusables": [{"term": term, "distinction": distinction} for term, distinction in locks],
        "sources": [{"label": source_label, "url": source_url}],
    }


LESSONS = [
    lesson(
        "POL-030", "John Winthrop", "1588-1649 | Massachusetts Bay leader",
        "A Puritan lawyer who transferred a chartered company into New England, repeatedly governed Massachusetts Bay, and framed the colony as a covenanted example watched by the world.",
        [
            ("Groton and the Cambridge Agreement, 1629", "This Suffolk landowner joined the Cambridge Agreement, whose signers promised to emigrate if the Massachusetts Bay charter and government moved with them. That transfer let the colony exercise unusual independence from London."),
            ("Governor before departure", "Company shareholders elected him governor before the migration. John Endecott had governed the small advance settlement, but this leader arrived with the much larger 1630 fleet."),
            ("The Arbella", "He crossed the Atlantic aboard this flagship in 1630. The fleet settled principally around Boston rather than remaining at the earlier Salem center."),
            ("A Model of Christian Charity", "This sermon described a community bound by mutual love and warned that failure would make the colonists a story and by-word. Its exact place of delivery is uncertain, despite its association with the Arbella."),
            ("City upon a hill", "His biblical image meant that the Puritan experiment would be publicly judged, not that Massachusetts possessed automatic national greatness. Ronald Reagan later transformed it into an optimistic American slogan."),
            ("Blessing of the Bay", "He owned this early colonial ship and participated with William Pynchon in the fur trade. Both are valuable clues beyond the famous sermon."),
            ("Roger Williams", "Although he opposed Williams's theology, he privately warned him that arrest was imminent in 1635. Williams escaped and founded Providence."),
            ("Anne Hutchinson and Henry Vane", "During the Antinomian Controversy, Hutchinson and young governor Henry Vane emphasized John Cotton's covenant-of-grace theology. This magistrate returned to office and supported Hutchinson's banishment."),
            ("The Pequot War, 1637", "He governed during the war that culminated in the Mystic massacre. That same year, the colony restricted political participation by Hutchinson's supporters."),
            ("Natural and civil liberty", "In a 1645 speech, he distinguished lawless natural liberty from civil or federal liberty exercised within a moral covenant. The distinction can open a political-thought question."),
            ("John the Younger", "His son became governor of Connecticut, led the Saybrook project, founded New London, and secured Connecticut's 1662 charter. Questions may ask for the surname shared by father and son."),
            ("The journal", "His detailed record of events from 1630 to 1649 became The History of New England. It is a major narrative source for early Massachusetts."),
            ("Repeated governorships and death", "He alternated the governorship with Endecott, Vane, Thomas Dudley, and Richard Bellingham. He died in Boston in 1649 while serving his final term."),
        ],
        {"6": ["Love and story-and-by-word passages", "Blessing of the Bay", "William Pynchon and John the Younger"], "5": ["Endecott and Henry Vane", "Roger Williams warning", "A Model of Christian Charity"], "4": ["Four-time governing periods", "Massachusetts Bay", "city upon a hill"]},
        [("John Winthrop the Younger", "The son governed Connecticut and was associated with Saybrook and New London."), ("John Endecott", "The advance-settlement governor preceded the 1630 fleet and later succeeded this leader."), ("William Bradford", "Bradford governed the separate Plymouth Colony and wrote Of Plymouth Plantation."), ("Roger Williams", "Williams was the dissenter whom this leader warned before his flight.")],
        "IAC: 2024 USHB national finals, direct answerline",
        "https://www.iacompetitions.com/wp-content/uploads/2024/04/US-History-Bee-2024-Varsity-and-JV-National-Championships-Finals.pdf",
    ),
    lesson(
        "POL-031", "Warren G. Harding", "1865-1923 | Twenty-ninth president",
        "An Ohio newspaper publisher elected on a return-to-normalcy promise whose short presidency combined naval diplomacy, conservative fiscal policy, civil-rights gestures, and several defining corruption scandals.",
        [
            ("The Marion Star", "He purchased this struggling Ohio newspaper in 1884 and built it into his political base. His wife Florence Kling Harding managed its circulation and finances with far more skill than the stereotype of a ceremonial spouse suggests."),
            ("Harry Daugherty and the smoke-filled room", "Political manager Daugherty predicted he could be nominated if the 1920 Republican convention deadlocked. Party leaders settled on him during negotiations remembered as the smoke-filled-room selection."),
            ("Return to normalcy", "His 1920 phrase promised stability after World War I, Wilsonian reform, strikes, and the Red Scare. The supposedly mistaken word normalcy had appeared in English before he used it."),
            ("The front-porch campaign", "He largely campaigned from Marion while delegations visited his home. He defeated James Cox and Franklin Roosevelt in the first presidential election after nationwide woman suffrage."),
            ("The Ohio Gang", "This label covered friends and political associates who gained access to the administration. It should evoke Daugherty, Jess Smith, Charles Forbes, and Albert Fall, though not every cabinet member was corrupt."),
            ("Teapot Dome", "Interior Secretary Albert Fall secretly leased naval petroleum reserves at Teapot Dome and Elk Hills to Harry Sinclair and Edward Doheny. Fall became the first former cabinet officer imprisoned for crimes committed in office."),
            ("Charles Forbes and the Veterans Bureau", "Forbes diverted supplies and manipulated hospital contracts before fleeing to Europe. His scandal showed that the administration's corruption extended beyond petroleum leases."),
            ("Washington Naval Conference", "Secretary of State Charles Evans Hughes opened the 1921-22 conference with dramatic ship-scrapping proposals. The resulting Five-Power Treaty imposed the famous 5:5:3 capital-ship ratio."),
            ("Budget and tariff", "He signed the Budget and Accounting Act of 1921, creating the Bureau of the Budget and General Accounting Office, and the protectionist Fordney-McCumber Tariff in 1922."),
            ("Phipps Act and Pershing Map", "The 1921 Federal Highway Act, often called the Phipps Act, concentrated federal aid on a connected primary-road system. His administration also commissioned the Pershing Map, which identified roads considered essential for national defense; IAC used both as early clues."),
            ("Eugene Debs", "On Christmas 1921 he commuted the socialist leader's wartime Espionage Act sentence. Debs then visited the White House, making the episode an unusual reconciliation clue."),
            ("Birmingham speech", "Speaking in segregated Alabama in 1921, he endorsed political equality for Black Americans while accepting social separation. The speech angered many white Southerners but fell far short of full racial equality."),
            ("Daugherty and Jess Smith", "Attorney General Harry Daugherty was his longtime political manager. Daugherty's aide Jess Smith operated from the Little Green House on K Street and died by suicide as influence-peddling allegations closed in, giving the Ohio Gang a second route beyond Teapot Dome."),
            ("Nan Britton and Carrie Phillips", "His affairs became lasting biographical routes. Genetic testing of descendants later supported Britton's claim that he fathered Elizabeth Ann Blaesing."),
            ("Voyage of Understanding and death", "During a 1923 western trip he became the first sitting president to visit Alaska. He died at San Francisco's Palace Hotel; Florence refused an autopsy, encouraging unfounded poisoning rumors."),
        ],
        {"6": ["Washington Conference and naval limitation", "Fordney-McCumber and radio proposals", "Nan Britton"], "5": ["Return to normalcy", "Albert Fall and petroleum leases", "Eugene Debs commutation"], "4": ["Teapot Dome", "Twenty-ninth president", "death in 1923 and Coolidge succession"]},
        [("Calvin Coolidge", "The vice president succeeded after the 1923 death and later won his own term."), ("Albert Fall", "The interior secretary took bribes and controlled the oil leases."), ("Harry Daugherty", "The attorney general and political manager was investigated but never convicted in the scandals."), ("Herbert Hoover", "The capable commerce secretary belonged to the cabinet but not the corrupt Ohio Gang.")],
        "IAC: 2023 USHB national finals, direct answerline",
        "https://www.iacompetitions.com/wp-content/uploads/2024/05/US-History-Bee-2023-Varsity-and-JV-National-Championships-Finals.pdf",
    ),
    lesson(
        "POL-032", "Jefferson Davis", "1808-1889 | Confederate president",
        "A West Point officer, Mexican War hero, senator, and secretary of war who became the Confederacy's only president, was imprisoned without trial, and spent his final years defending secession.",
        [
            ("Kentucky birth and West Point", "He was born in Kentucky less than a year and roughly one hundred miles from Abraham Lincoln. At West Point he narrowly avoided punishment for his role in the 1826 Eggnog Riot."),
            ("Black Hawk escort", "After graduating in 1828, he served on the northwestern frontier. During the Black Hawk War, he helped escort the captured Black Hawk to confinement, an early military clue IAC has used before any mention of Mississippi politics."),
            ("Sarah Knox Taylor", "While serving under Zachary Taylor, he married the commander's daughter Sarah Knox. Both contracted malaria at Locust Grove, and she died only three months after the wedding."),
            ("Brierfield and Joseph Davis", "His wealthy brother Joseph established him at Brierfield plantation on Davis Bend, Mississippi. Enslaved labor supported the plantation and his return to public life."),
            ("Varina Howell, 1845", "After nearly a decade as a planter, he married Varina Howell and entered Congress in 1845. Varina became the Confederacy's first lady and later wrote Jefferson Davis: A Memoir by His Wife."),
            ("Mississippi Rifles", "He commanded this volunteer regiment in the Mexican-American War. At Buena Vista his troops used a V-shaped formation, and he suffered a serious foot wound."),
            ("Congress and Guadalupe Hidalgo", "Mississippi sent the wounded war hero to the Senate in 1847, where he chaired the Military Affairs Committee. He proposed an unsuccessful amendment to the Treaty of Guadalupe Hidalgo that would have taken additional parts of Tamaulipas, Nuevo Leon, Coahuila, and Chihuahua."),
            ("Franklin Pierce's secretary of war", "From 1853 to 1857 he enlarged and modernized the army, supported surveys for a transcontinental railroad, and oversaw the experimental Camel Corps."),
            ("Railroad surveys, aqueduct, and Gadsden", "His department commissioned the Pacific Railroad Surveys, promoted the southern route associated with the Gadsden Purchase, and supervised construction of the Washington Aqueduct. These projects form a second War Department route independent of the camels."),
            ("Crimean War observers", "He sent Richard Delafield, Alfred Mordecai, and George B. McClellan to observe European armies during the Crimean War. McClellan's later Union career makes this a particularly useful prewar clue."),
            ("Senate resignation", "He had defended slavery and states' rights but initially regarded immediate secession as strategically dangerous. He resigned from the Senate after Mississippi left the Union in January 1861."),
            ("Committee of Thirteen and farewell", "He joined the Senate Committee of Thirteen that unsuccessfully sought a final sectional compromise. On January 21, 1861, he delivered an emotional farewell arguing that Mississippi had exercised a lawful right of secession."),
            ("Chosen at Montgomery", "The provisional Confederate Congress selected him president despite his preference for military command. He later won a six-year term under the Confederate Constitution."),
            ("Richmond White House", "He governed from the Confederate White House after the capital moved from Montgomery. His vice president was Alexander Stephens; major cabinet figures included Judah Benjamin and Robert Toombs."),
            ("Cabinet map", "Robert Toombs began as secretary of state, Stephen Mallory remained navy secretary, and Judah Benjamin moved from attorney general to war and then state. Remembering those offices prevents every Confederate-cabinet clue from collapsing into the same name."),
            ("Johnston and Bragg", "His difficult relationship with Joseph E. Johnston damaged Confederate command, while his continued confidence in Braxton Bragg generated further controversy. These names can identify his wartime leadership."),
            ("Lee after Seven Pines", "After Joseph E. Johnston was wounded at Seven Pines in 1862, he placed Robert E. Lee in direct command of the force Lee renamed the Army of Northern Virginia. Davis remained the civilian commander in chief, not Lee's field subordinate."),
            ("Conscription and centralization", "The Confederacy adopted national conscription, taxation, impressment, and suspension of habeas corpus. These measures exposed the tension between states' rights rhetoric and wartime central power."),
            ("Brown, Vance, and governors", "Georgia governor Joseph E. Brown and North Carolina governor Zebulon Vance resisted conscription, impressment, and habeas suspensions. Their disputes with the Confederate president are the clearest route into his centralization problem."),
            ("Dahlgren papers", "Alleged orders found after Ulric Dahlgren's failed 1864 raid called for burning Richmond and killing Davis and his cabinet. Their authenticity remains disputed, so treat this as the Dahlgren Affair rather than a proven assassination order."),
            ("General Orders No. 14", "Only in March 1865 did his government authorize recruiting enslaved men with owners' consent. The measure came too late to produce a meaningful Confederate Black force and did not itself grant general emancipation."),
            ("Capture and the petticoat story", "Union cavalry captured him near Irwinville, Georgia, in 1865. He wore his wife's waterproof outer garment while escaping, which Northern cartoons transformed into the false claim that he disguised himself as a woman."),
            ("Fort Monroe", "He spent two years imprisoned there, initially in shackles, under commandant Nelson A. Miles. He was indicted for treason but never tried, partly because a trial risked testing the constitutionality of secession."),
            ("The hundred-thousand-dollar bond", "Horace Greeley, Gerrit Smith, Cornelius Vanderbilt, and other prominent men backed his 1867 bail. Greeley's participation angered many longtime Tribune readers and abolitionist allies."),
            ("Virginia Clay correspondence", "While imprisoned, he exchanged an intimate three-year correspondence with Virginia Clay, whose husband Clement Claiborne Clay was also held at Fort Monroe. IAC used reports that the two later appeared together on a train as an early biographical clue."),
            ("Sarah Dorsey and Beauvoir", "Widow Sarah Anne Ellis Dorsey hosted him at Beauvoir and left the Mississippi estate to him in her will. His residence there produced gossip and supplied the setting where he completed his defense of the Confederacy."),
            ("Varina, Beauvoir, and his defense", "His second wife Varina Howell survived him. At Beauvoir in Mississippi he wrote The Rise and Fall of the Confederate Government, presenting secession as constitutional and minimizing slavery's centrality."),
            ("Carter's 1978 resolution", "Jimmy Carter signed a congressional resolution restoring Davis's full rights of citizenship posthumously in 1978. IAC has paired that modern clue with the Camel Corps, Eggnog Riot, and bail bond."),
        ],
        {"6": ["Eggnog Riot and Black Hawk escort", "Sarah Knox Taylor, Brierfield, and Virginia Clay", "Camel Corps, Pacific Railroad Surveys, and Crimean observers", "Dahlgren papers", "Sarah Dorsey and Beauvoir"], "5": ["Mississippi Rifles at Buena Vista", "Petticoat capture rumor", "Pierce cabinet and Gadsden Purchase", "Toombs, Mallory, and Judah Benjamin", "Greeley-Vanderbilt bail bond"], "4": ["Richmond White House", "only Confederate president", "Fort Monroe imprisonment", "Alexander Stephens and Robert E. Lee", "Irwinville capture"]},
        [("Jefferson Davis", "The Confederate president; do not confuse him with Union general Jefferson Columbus Davis, who killed fellow Union general William Bull Nelson."), ("Alexander Stephens", "The Confederate vice president and Cornerstone Speech author."), ("Judah Benjamin", "The cabinet member who successively served as attorney general, war secretary, and secretary of state."), ("Joseph E. Johnston", "The general who repeatedly clashed with Davis; Albert Sidney Johnston was the commander Davis personally admired."), ("Zachary Taylor", "His first wife's father and his commander before the Mexican War.")],
        "IAC: 2018 USHB national playoff round 1, direct answerline",
        "https://www.iacompetitions.com/wp-content/uploads/2023/09/2018-HS-Nationals-US-History-Bee-Playoff-Round-1.pdf",
    ),
    lesson(
        "LAW-005", "Oliver Wendell Holmes Jr.", "1841-1935 | Supreme Court justice",
        "A wounded Civil War officer and legal theorist whose opinions shaped free-speech doctrine, judicial restraint, and American legal realism, while also including the notorious eugenics decision Buck v. Bell.",
        [
            ("The other Oliver Wendell Holmes", "His father was the physician and poet who wrote Old Ironsides. The son added Jr. and became the jurist, making profession clues essential."),
            ("Twentieth Massachusetts", "He fought with this regiment and was wounded at Ball's Bluff, Antietam, and Chancellorsville. A famous but unverified story has him shouting at Abraham Lincoln to take cover at Fort Stevens."),
            ("Theodore Roosevelt friendship", "He knew Theodore Roosevelt from Boston reform circles and corresponded with him before the presidency. Roosevelt appointed him in 1902 but later felt betrayed when the justice dissented in Northern Securities."),
            ("The Common Law, 1881", "This book opens with the idea that the life of the law has been experience rather than logic. It made him an intellectual ancestor of legal realism."),
            ("The Path of the Law, 1897", "This lecture described law from the viewpoint of a bad man concerned with predicting what courts will actually do. It separated legal analysis from morality and became another foundational legal-realist text."),
            ("Massachusetts bench", "He served on the Massachusetts Supreme Judicial Court and became its chief justice before Theodore Roosevelt appointed him to the U.S. Supreme Court in 1902."),
            ("The Great Dissenter", "His short, forceful dissents frequently became more influential than the majorities they opposed. The nickname particularly fits his economic and free-speech opinions."),
            ("Lochner dissent", "He rejected the Court's use of liberty of contract to invalidate a bakers' hours law, writing that the Fourteenth Amendment did not enact Herbert Spencer's Social Statics."),
            ("Schenck and clear and present danger", "His unanimous 1919 opinion upheld punishment of anti-draft leaflets. The crowded-theater analogy came from this restrictive decision, not from a broad defense of speech."),
            ("Abrams dissent", "Later in 1919 he argued that truth should prevail through competition in the marketplace of ideas. Zechariah Chafee and Judge Learned Hand likely influenced his shift."),
            ("Gitlow dissent with Brandeis", "In Gitlow v. New York, the Court assumed speech protections applied to states but upheld a criminal-anarchy conviction. Holmes and Brandeis dissented because Benjamin Gitlow's manifesto posed no present danger."),
            ("Baltzer dissent", "The Court declined to publish his dissent from dismissal of Baltzer v. United States, which challenged punishment of German-American draft opponents. His secretary circulated it privately, and its defense of dissent anticipated the more famous Abrams opinion."),
            ("Debs and Frohwerk", "Along with Schenck, these cases formed a trilogy upholding wartime Espionage Act convictions. Do not assume every opinion associated with him protected dissenters."),
            ("Northern Securities", "He dissented when the Court broke up J. P. Morgan's railroad combination. Theodore Roosevelt regarded the vote as a personal betrayal by his appointee."),
            ("Pennsylvania Coal and Missouri v. Holland", "He wrote that regulation can become a taking when it goes too far in Pennsylvania Coal, but upheld federal treaty power over migratory birds in Missouri v. Holland. The pairing shows why his federalism cannot be reduced to one slogan."),
            ("Silverthorne", "His opinion excluded illegally seized evidence and its derivatives, helping establish the principle later called fruit of the poisonous tree."),
            ("Olmstead dissent map", "The famous right-to-be-let-alone wiretap dissent in Olmstead belongs to Louis Brandeis, not Holmes. Holmes also dissented, calling the government's use of illegally obtained evidence dirty business."),
            ("Buck v. Bell", "He wrote the 1927 majority upholding Virginia's compulsory sterilization law and declared that three generations of imbeciles were enough. This is the central dark counterweight to his civil-liberties reputation."),
            ("Frankfurter and the secretaries", "Young lawyers including Felix Frankfurter served as his secretaries and helped transmit his influence into the next generation of American law. His correspondence with Harold Laski also became an important intellectual record."),
            ("Retirement at ninety", "He left the Court in 1932 after nearly three decades and remains among its oldest-serving justices. He died in 1935, leaving much of his estate to the United States."),
        ],
        {"6": ["Baltzer and Zechariah Chafee", "bad man in The Path of the Law", "Twentieth Massachusetts wounds", "Pennsylvania Coal and Missouri v. Holland", "Silverthorne derivatives"], "5": ["Herbert Spencer in Lochner", "wartime speech trilogy", "Abrams marketplace dissent", "Northern Securities and Roosevelt", "Buck v. Bell"], "4": ["clear and present danger", "crowded-theater analogy", "The Common Law", "Great Dissenter", "Supreme Court justice"]},
        [("Oliver Wendell Holmes Sr.", "The father was a physician and poet; the son was the justice."), ("Louis Brandeis", "Brandeis wrote the major privacy dissent in Olmstead and joined later speech dissents."), ("Learned Hand", "A lower-court judge whose Masses opinion influenced free-speech thinking."), ("John Marshall Harlan", "The earlier Great Dissenter is associated with Plessy and the Civil Rights Cases.")],
        "IAC: 2018 USHB national playoff round 1, direct answerline",
        "https://www.iacompetitions.com/wp-content/uploads/2023/09/2018-HS-Nationals-US-History-Bee-Playoff-Round-1.pdf",
    ),
    lesson(
        "COL-004", "William Penn", "1644-1718 | Quaker proprietor",
        "An English Quaker writer and advocate for religious liberty whose royal land grant produced Pennsylvania, Philadelphia's planned grid, and a comparatively conciliatory early relationship with the Lenape.",
        [
            ("Admiral Sir William Penn", "His father was a prominent naval commander and creditor of Charles II. The king's grant of Pennsylvania in 1681 helped settle the Crown's debt to the father."),
            ("Thomas Loe and George Fox", "Quaker missionary Thomas Loe influenced him in Ireland, and he became a follower of movement founder George Fox. His conversion brought expulsion, imprisonment, and conflict with his family."),
            ("No Cross, No Crown", "This 1669 prison treatise defended Quaker spirituality and plain conduct, including refusal of flattering titles and insistence on addressing individuals as thou."),
            ("The Sandy Foundation Shaken", "This 1668 tract attacked conventional formulations of the Trinity and led to his imprisonment in the Tower of London. He answered charges of atheism with Innocency with Her Open Face, clarifying his theology without abandoning Quaker beliefs."),
            ("Truth Exalted", "His 1668 Truth Exalted: To Princes, Priests, and People attacked established churches and lists such as Ursulines, Capuchins, and Benedictines. Those unusual names have already served as an IAC opening route."),
            ("Penn and Mead trial", "A London jury refused to convict him and William Mead for unlawful preaching. The punishment of the jurors produced Bushel's Case, a landmark for jury independence."),
            ("William Mead and Bushel's Case", "Juror Edward Bushel refused to change the acquittal despite judicial pressure. The resulting 1670 decision established that jurors could not be punished merely for reaching an unwanted verdict."),
            ("The Great Case of Liberty of Conscience", "This tract argued that coercion in religion violated both Christianity and natural rights. Religious toleration was foundational to his colonial plan."),
            ("Pennsylvania, 1681", "He preferred New Wales or Sylvania, but Charles II named the province Pennsylvania in honor of the admiral. The proprietor feared observers would think he had named it for himself."),
            ("Delaware's lower counties", "The Duke of York transferred the lower counties on the Delaware to him in 1682, giving the province ocean access. They shared a governor with Pennsylvania but developed a separate assembly and eventually became Delaware."),
            ("The Holy Experiment", "The colony was intended to demonstrate representative government, toleration, and Quaker principles while also generating income for its proprietor."),
            ("Frame and Charter", "The 1682 Frame of Government established an elected assembly and complex councils. The 1701 Charter of Privileges strengthened the assembly and provided broad religious liberty for monotheists."),
            ("Great Law of 1682", "The first assembly adopted a legal code that limited capital crimes and protected worship while retaining unequal political rules. It converted the Holy Experiment from a slogan into a functioning government."),
            ("Philadelphia and Thomas Holme", "Surveyor Thomas Holme translated the proprietor's plan into a grid between the Delaware and Schuylkill. Major streets were named for trees, and public squares punctuated the plan."),
            ("Penn's landing and first assembly", "He arrived aboard the Welcome in 1682 and called the first assembly at Chester, formerly Upland. Philadelphia was planned soon afterward as a green country town rather than an inherited medieval city."),
            ("Tamanend and Shackamaxon", "Tradition associates him with a peace agreement beneath an elm at Shackamaxon with Lenape leader Tamanend. No surviving written treaty proves the celebrated scene."),
            ("Mason-Dixon background", "His heirs repeatedly disputed Pennsylvania's southern boundary with the Calvert proprietors of Maryland. That conflict eventually produced the Mason-Dixon survey, although it occurred after his death."),
            ("Walking Purchase correction", "The fraudulent 1737 Walking Purchase occurred nineteen years after his death and was arranged by his sons and colonial officials. It should identify Pennsylvania's later proprietors, not an agreement personally made by him."),
            ("Pennsbury and two visits", "He resided at Pennsbury Manor during visits from 1682 to 1684 and 1699 to 1701. Most of his proprietary administration occurred from England."),
            ("Debt, stroke, and death", "Fraud by agent Philip Ford helped place him in debtors' prison. Strokes beginning in 1712 incapacitated him, and he died at Ruscombe in 1718."),
        ],
        {"6": ["Truth Exalted and named religious orders", "Thomas Loe and Philip Ford", "Penn and Mead jury trial", "The Sandy Foundation Shaken", "No Cross, No Crown"], "5": ["Charter of Privileges and Great Law", "Thomas Holme and tree streets", "Tamanend and Shackamaxon", "Welcome and Chester assembly", "lower counties on the Delaware"], "4": ["Quaker proprietor", "Philadelphia", "namesake colony on the Delaware", "Charles II debt to his father", "religious liberty"]},
        [("Admiral William Penn", "The father was the naval commander whose unpaid royal debt helped produce the grant."), ("Thomas Penn", "The son participated in the later Walking Purchase."), ("George Fox", "Fox founded the Quaker movement; this proprietor became its politically connected defender."), ("Roger Williams", "Williams founded Rhode Island around liberty of conscience but was not a Quaker proprietor.")],
        "IAC: 2021 USHB regional semifinal direct answerline and repeated national preliminaries",
        "https://www.iacompetitions.com/wp-content/uploads/2023/09/2020-2021-HS-US-History-Bee-Semifinals-B-Set.pdf",
    ),
    lesson(
        "POL-033", "Thomas Jefferson", "1743-1826 | Third president",
        "A Virginia planter, revolutionary writer, diplomat, party founder, president, architect, and university builder whose language of liberty coexisted with slaveholding and the exploitation of the Hemings family.",
        [
            ("Shadwell, William and Mary, George Wythe", "Born at Shadwell, he studied at the College of William and Mary and read law under George Wythe. Wythe linked him to Virginia's legal and classical intellectual tradition."),
            ("A Summary View, 1774", "This pamphlet argued that colonists possessed rights independent of Parliament and addressed George III as the empire's chief officer. It established his reputation before independence."),
            ("Declaration draft", "The Committee of Five assigned him the first draft. Congress removed his long attack on the slave trade and revised other language before adopting the document."),
            ("Virginia Statute for Religious Freedom", "He drafted this measure in 1777, and James Madison secured its passage in 1786. It disestablished the Anglican Church and declared that civil rights should not depend on religious belief, one of the three achievements named on his epitaph."),
            ("Virginia governor and Arnold's raid", "While governor, he fled Richmond as Benedict Arnold's British force approached in 1781. Critics later used the episode to question his wartime leadership."),
            ("Notes on the State of Virginia", "Organized as responses to Francois Barbe-Marbois, this book covers geography, government, and natural history while exposing his racist assumptions and anxieties about slavery."),
            ("Buffon, the moose, and Megalonyx", "He rejected Georges-Louis Leclerc de Buffon's claim that American nature was degenerate and shipped him an enormous moose. Fossil claws led him to name Megalonyx, initially imagining a giant living lion before recognizing a ground sloth."),
            ("Banneker and Gregoire", "Benjamin Banneker sent him an almanac in 1791 while challenging his racial views; he replied that he wished to see evidence of equal Black talents. He later dismissed Henri Gregoire's account of Black achievement in similarly revealing correspondence."),
            ("Paris, Maria Cosway, and the Hemingses", "As minister to France he wrote the Head and Heart dialogue to Maria Cosway. Sally Hemings accompanied his household, and strong historical and genetic evidence identifies him as father of her children."),
            ("James Callender", "He secretly subsidized journalist James Thomson Callender's attacks on the Adams administration, then refused him a federal appointment. Callender retaliated by publicizing the president's relationship with Sally Hemings in 1802."),
            ("Hamilton's rival", "As Washington's secretary of state he opposed assumption, the national bank, and a pro-British foreign policy. His alliance with James Madison created the Democratic-Republican opposition."),
            ("Citizen Genet and resignation", "French envoy Edmond-Charles Genet tried to commission privateers and appeal directly to Americans despite Washington's neutrality. Jefferson defended France more than Hamilton did but ultimately joined the cabinet request for Genet's recall and resigned at the end of 1793."),
            ("Kentucky Resolutions", "After the Alien and Sedition Acts, he secretly drafted Kentucky's resolutions while Madison wrote Virginia's. Their compact reasoning later fed nullification arguments."),
            ("Mazzei letter", "In an unpublished 1796 letter to Philip Mazzei, he complained that an Anglican, monarchical, and aristocratic party had arisen around Washington. Federalist newspapers printed it, making it evidence of his break with the first president."),
            ("Danbury Baptists", "In an 1802 letter to Connecticut Baptists, he described the First Amendment as building a wall of separation between church and state. The phrase became far more influential through later Supreme Court opinions."),
            ("Revolution of 1800", "The electoral tie with Aaron Burr sent the election to the House, where Hamilton preferred him. The crisis produced the Twelfth Amendment's separate presidential and vice-presidential ballots."),
            ("Barbary War", "He rejected continuing tribute to Tripoli and sent naval forces to the Mediterranean. The conflict included the burning of the captured Philadelphia and the march to Derna."),
            ("Louisiana and Lewis and Clark", "He purchased Louisiana despite doubts that the Constitution authorized acquiring territory. Meriwether Lewis and William Clark then explored the trans-Mississippi West."),
            ("Constitutional amendment abandoned", "He initially considered an amendment necessary to authorize the Louisiana Purchase, then abandoned that scruple when delay threatened the agreement. The contrast between strict construction and rapid acquisition is the point of this clue."),
            ("Embargo", "The 1807 ban on American overseas commerce attempted peaceful coercion after British and French violations. Smuggling and economic pain made it one of his presidency's greatest failures."),
            ("Chesapeake-Leopard aftermath", "After HMS Leopard attacked USS Chesapeake in 1807, he rejected immediate war and instead pursued economic coercion through the Embargo Act. Congress replaced it with the Non-Intercourse Act as he left office."),
            ("Jefferson Bible", "He cut and pasted passages from the Gospels into The Life and Morals of Jesus of Nazareth, removing miracles and the Resurrection while preserving ethical teachings. IAC may describe this literally edited New Testament."),
            ("Adam and Eve letter", "In a 1793 letter to William Short defending the French Revolution, he wrote that even half the earth desolated and only an Adam and Eve left in every country could be preferable to failed liberty. The extreme language opened an IAC presidential question."),
            ("Final Jubilee letter", "Too ill to attend the fiftieth-anniversary celebration in Washington, D.C., he sent Mayor Roger Weightman a final public letter calling the Declaration an instrument pregnant with the fate of the world. He died ten days later on July 4, 1826."),
            ("Monticello, the university, and July Fourth", "He designed Monticello and the University of Virginia's Academical Village and wanted both achievements, plus religious freedom, on his tomb. He died on July 4, 1826, the same day as John Adams."),
            ("Rotunda and Academical Village", "For the University of Virginia, he arranged faculty and students around the Lawn and modeled the Rotunda on the Roman Pantheon. The Rockfish Gap Commission supplied the institutional plan, while the architecture supplies a separate visual route."),
        ],
        {"6": ["Gregoire and Banneker letters", "Head and Heart to Maria Cosway", "Buffon moose and Megalonyx", "Mazzei and William Short letters", "final Jubilee letter"], "5": ["Danbury Baptists and wall of separation", "Kentucky Resolutions", "Notes on Virginia", "James Callender", "Virginia religious-freedom statute"], "4": ["Declaration of Independence", "Louisiana Purchase", "Revolution of 1800", "Monticello and University of Virginia", "third president"]},
        [("Thomas Jefferson", "The president and Declaration drafter; do not confuse him with Confederate president Jefferson Davis."), ("James Madison", "Madison wrote the Virginia Resolutions and shared party leadership but drafted the Constitution, not the Declaration."), ("George Wythe", "The mentor and first American law professor."), ("Benjamin Banneker", "The Black surveyor and almanac author who challenged this founder's racial assumptions.")],
        "IAC: 2019 National History Bowl national playoff round 5, direct answerline",
        "https://www.iacompetitions.com/wp-content/uploads/2023/08/2019-HS-Nationals-History-Bowl-Playoff-Round-5.pdf",
    ),
    lesson(
        "POL-034", "William Howard Taft", "1857-1930 | President and chief justice",
        "A judge and colonial administrator who succeeded Theodore Roosevelt, fractured the Republican Party, and later achieved his preferred office as the only former president to serve as chief justice.",
        [
            ("Alphonso Taft and Cincinnati", "His father served as attorney general and secretary of war under Grant. The younger man built his early career through Ohio judgeships rather than through electoral campaigning."),
            ("Solicitor general and circuit judge", "Benjamin Harrison appointed him solicitor general in 1890 and then to the Sixth Circuit. He repeatedly preferred judicial work to partisan politics."),
            ("Philippine Commission", "McKinley sent him to organize civil government, and in 1901 he became the first civilian governor-general of the Philippines. His paternal language about little brown brothers reflected imperial assumptions."),
            ("The Vatican mission", "He negotiated with Pope Leo XIII over purchasing friar lands in the Philippines. The mission made church property and colonial administration useful early clues."),
            ("Taft-Katsura memorandum", "During a 1905 Asian trip, he discussed Korea and the Philippines with Japanese prime minister Katsura Taro. Their memorandum recorded parallel understandings rather than a formal secret treaty trading control of the two places."),
            ("Secretary of war and Cuba", "He succeeded Elihu Root in Roosevelt's cabinet, supervised Philippine and canal matters, and briefly served as provisional governor of Cuba after Tomas Estrada Palma's government collapsed."),
            ("Roosevelt's chosen successor", "Roosevelt promoted him for the 1908 Republican nomination. Their friendship broke when progressives concluded that the new administration had betrayed Roosevelt's program."),
            ("Election of 1908", "He defeated William Jennings Bryan with James S. Sherman as his running mate. His wife Helen Herron Taft, known as Nellie, strongly encouraged the presidential career he personally valued less than judicial service."),
            ("Dollar Diplomacy", "Secretary of State Philander Knox encouraged American investment to extend influence, especially in Latin America and China. Intervention in Nicaragua became a defining example."),
            ("Payne-Aldrich", "He praised this tariff as the best Republicans had passed, alienating insurgent progressives who expected deeper reductions. The dispute helped split the party."),
            ("Ballinger-Pinchot", "He supported Interior Secretary Richard Ballinger and dismissed conservationist Gifford Pinchot after Pinchot publicly attacked Ballinger. The controversy accelerated Roosevelt's break with him."),
            ("Louis Glavis", "General Land Office investigator Louis Glavis accused Ballinger of improperly favoring Alaskan coal claimants. His dismissal and publication of the charges in Collier's turned a technical land dispute into the administration's defining conservation scandal."),
            ("More antitrust cases", "His administration filed more antitrust suits than Roosevelt's, including actions against Standard Oil and American Tobacco. Yet Roosevelt criticized its case against U.S. Steel."),
            ("Mann-Elkins and postal banking", "The Mann-Elkins Act strengthened Interstate Commerce Commission authority over railroad and communications rates. His administration also established the Postal Savings System, giving small depositors a government-backed alternative to private banks."),
            ("Sixteenth Amendment and new states", "Congress proposed the federal income-tax amendment during his presidency, and it was ratified in 1913. New Mexico and Arizona entered the Union in 1912, completing the contiguous forty-eight states."),
            ("The election of 1912", "Roosevelt's Progressive Party split Republican voters. The incumbent finished third behind Woodrow Wilson and Roosevelt, carrying only Utah and Vermont."),
            ("Archibald Butt and the Titanic", "He urged his exhausted military aide Archibald Butt to take a vacation in 1912. Butt died returning aboard the Titanic, and the president was reportedly devastated by the loss."),
            ("Chief justice, 1921", "Harding appointed him to succeed Edward Douglass White. He remains the only person to have headed both the executive branch and the Supreme Court."),
            ("The Taft Court", "His Court upheld zoning in Village of Euclid, struck down a minimum-wage law in Adkins, and applied free speech against the states in Gitlow. Its bench included Holmes, Brandeis, McReynolds, and Van Devanter; serial killer Carl Panzram later used a gun stolen from the chief justice's New Haven home, an especially distinctive IAC clue."),
            ("Appointments and Edward Douglass White", "As president he made six Supreme Court appointments and elevated Edward Douglass White to chief justice. Only Washington and Franklin Roosevelt appointed more justices; Harding later appointed the former president to succeed White."),
            ("Judges' Bill and Supreme Court building", "He championed the Judiciary Act of 1925, which expanded discretionary certiorari, and pressed for a separate Supreme Court building. He died before the building opened."),
            ("Baseball and bathtub myth", "He began the presidential tradition of throwing a ceremonial first pitch in 1910. The familiar story that he became stuck in a White House bathtub is unsupported and should be treated as caricature, not a reliable biographical fact."),
        ],
        {"6": ["Provisional governor after Estrada Palma", "Vatican friar-land mission", "Taft-Katsura memorandum", "Carl Panzram's stolen gun", "Archibald Butt"], "5": ["Philippine civil governor", "Elihu Root succession", "Ballinger, Glavis, and Pinchot", "Philander Knox and Dollar Diplomacy", "Judges' Bill of 1925"], "4": ["Twenty-seventh president", "chief justice", "only person to lead presidency and Court", "Roosevelt split in 1912", "Payne-Aldrich Tariff"]},
        [("Theodore Roosevelt", "The predecessor and former ally who ran as a Progressive in 1912."), ("Charles Evans Hughes", "A later chief justice and 1916 nominee, not a president."), ("Edward Douglass White", "The chief justice whom this former president succeeded in 1921."), ("Robert Taft", "His son became the conservative Ohio senator known as Mr. Republican.")],
        "IAC: 2019 National History Bowl national playoff round 1, direct answerline",
        "https://www.iacompetitions.com/wp-content/uploads/2023/08/2019-HS-Nationals-History-Bowl-Playoff-Round-1.pdf",
    ),
    lesson(
        "POL-035", "Alexander Hamilton", "c. 1755-1804 | Treasury founder",
        "A Caribbean-born revolutionary officer, constitutional polemicist, and first treasury secretary who built the federal financial system, led the early Federalists, and died after a duel with Aaron Burr.",
        [
            ("Nevis, St. Croix, and the hurricane letter", "Born out of wedlock in the Caribbean, he clerked for Beekman and Cruger on St. Croix. A vivid 1772 hurricane account helped patrons send him to mainland North America for education."),
            ("King's College and the Hearts of Oak", "He studied at the future Columbia University and joined a New York militia company. As an artillery officer he fought at Trenton and Princeton."),
            ("Washington's aide and Laurens", "He became Washington's principal aide-de-camp, managing correspondence and intelligence. His intense friendship with John Laurens and frustration with staff work are frequent biographical routes."),
            ("Yorktown Redoubt Ten", "After demanding a field command, he led the nighttime bayonet assault on British Redoubt Number Ten. French troops simultaneously captured Number Nine."),
            ("Newburgh and Continentalist essays", "After Yorktown he represented New York in the Confederation Congress and wrote Continentalist essays calling for stronger national taxing power. During the Newburgh crisis, he communicated with dissatisfied officers while Washington ultimately defused the confrontation."),
            ("Eliza Schuyler", "His marriage joined him to Philip Schuyler's powerful New York family. Eliza later preserved his papers and helped establish the Orphan Asylum Society."),
            ("Seabury pamphlet battle", "He answered loyalist Samuel Seabury's Letters of a Westchester Farmer with A Full Vindication and The Farmer Refuted. These youthful writings opened IAC's 2018 playoff question."),
            ("Annapolis Convention", "He attended the poorly subscribed 1786 meeting on interstate commerce and helped James Madison draft its call for a broader convention at Philadelphia. That recommendation became the immediate institutional bridge to the Constitutional Convention."),
            ("Constitution and Publius", "At Philadelphia he advocated an extremely strong executive and Senate. He then wrote most of the Federalist essays alongside James Madison and John Jay."),
            ("Federalist authorship map", "He wrote fifty-one of the eighty-five Federalist essays; Madison wrote twenty-nine and Jay five. Hamilton handled many institutional and executive topics, including the energetic executive in Federalist No. 70."),
            ("New York ratification", "At the Poughkeepsie convention, he debated Anti-Federalists led by Governor George Clinton and Melancton Smith. New York ratified narrowly after recommending amendments and reserving confidence in the new union."),
            ("Public credit and assumption", "As treasury secretary he proposed funding federal securities at face value and assuming state Revolutionary debts. The measures tied creditors to the new government."),
            ("The dinner-table compromise", "Jefferson hosted the meeting at which Madison accepted assumption while northern leaders accepted a permanent Potomac capital. This became the Compromise of 1790."),
            ("Bank and implied powers", "His defense of the First Bank argued that necessary means could be implied from enumerated powers. Washington accepted his reasoning over Jefferson's strict construction."),
            ("Manufactures, customs, and cutters", "His Report on Manufactures promoted industrial development, while his department created customs administration and the Revenue Cutter Service, an ancestor of the Coast Guard."),
            ("Whiskey tax and rebellion", "His excise on distilled spirits fell heavily on western producers and helped provoke the Whiskey Rebellion. He accompanied Washington's militia mobilization in 1794, demonstrating the enforcement power of the financial state he had designed."),
            ("Paterson and the useful-manufactures society", "He helped found the Society for Establishing Useful Manufactures, which planned the industrial city of Paterson around the Passaic Falls. Treasury aide Tench Coxe contributed research and drafting to his reports before later changing parties."),
            ("Reynolds Pamphlet", "To rebut corruption charges involving James Reynolds, he publicly admitted an affair with Maria Reynolds. The confession protected his financial reputation while destroying his family and political standing."),
            ("Clingman and Monroe", "James Monroe, Frederick Muhlenberg, and Abraham Venable confronted him with accusations carried by James Reynolds and Jacob Clingman. Hamilton showed them evidence of the affair, then later blamed Monroe when the story became public."),
            ("Camillus and Jay's Treaty", "Under the name Camillus, he wrote an extended defense of Jay's Treaty against attacks from Jeffersonian Republicans. The essays linked his constitutional argument for executive treaty power to a strongly pro-British commercial policy."),
            ("The New-York Evening Post", "He and allied investors founded the newspaper in 1801 to give Federalists a New York voice; William Coleman became its first editor. The paper survives as the New York Post."),
            ("Quasi-War army", "During the undeclared naval conflict with France, Washington became nominal commander of a provisional army and insisted on him as the active second-in-command. Adams distrusted the resulting military buildup and his ambitions, deepening their fatal Federalist split."),
            ("The 1800 Adams pamphlet", "He privately circulated a sweeping attack on John Adams's character and conduct, but Aaron Burr's allies obtained and published it. The episode split Federalists during the election and helped destroy Hamilton's remaining party leadership."),
            ("Philip Hamilton and the Eacker duel", "His eldest son Philip died after a duel with George Eacker in 1801, using pistols later associated with the father's duel. Eliza was pregnant with a second son whom the family also named Philip."),
            ("Adams, Burr, and Weehawken", "He helped Jefferson defeat Burr in the House contest of 1801 and opposed Burr's 1804 New York gubernatorial bid. After Charles D. Cooper publicized a supposedly despicable opinion, Burr demanded satisfaction and fatally wounded him at Weehawken."),
        ],
        {"6": ["grave and phlegmatic pamphlet voice", "Letters of a Westchester Farmer", "Tench Coxe and Paterson", "Camillus essays", "Newburgh correspondence"], "5": ["Samuel Seabury and The Farmer Refuted", "A Full Vindication", "Revenue Cutter and reports", "Poughkeepsie ratification", "Reynolds and Clingman"], "4": ["Federalist Papers", "first treasury secretary", "national bank and public credit", "Compromise of 1790", "Burr duel"]},
        [("Alexander Hamilton", "The treasury secretary; do not confuse him with later vice president Alexander Hamilton Stephens."), ("James Madison", "The Federalist coauthor who later opposed the financial program."), ("Philip Schuyler", "His father-in-law, senator, and New York political ally."), ("Aaron Burr", "The electoral rival and duelist who killed him.")],
        "IAC: 2018 USHB national playoff round 1, direct answerline",
        "https://www.iacompetitions.com/wp-content/uploads/2023/09/2018-HS-Nationals-US-History-Bee-Playoff-Round-1.pdf",
    ),
]

LESSONS += [
    lesson(
        "MISC-050", "Horace Greeley", "1811-1872 | Editor and presidential candidate",
        "A reform-minded newspaper editor who built the New-York Tribune, promoted western settlement and antislavery politics, pressed Lincoln toward emancipation, and died after losing the 1872 election.",
        [
            ("Printer from New Hampshire", "Born in Amherst, New Hampshire, he apprenticed at the Northern Spectator in East Poultney, Vermont. His distinctive appearance and intense work habits became part of his public persona."),
            ("Log Cabin and the Tribune", "He edited a campaign paper supporting William Henry Harrison in 1840, then founded the New-York Tribune in 1841 with Thomas McElrath."),
            ("The New-Yorker and the Jeffersonian", "Before the Tribune, he edited a literary weekly called The New-Yorker, unrelated to the modern magazine. Thurlow Weed then recruited him to edit the Jeffersonian and Log Cabin for New York Whigs."),
            ("Margaret Fuller and Whitelaw Reid", "Fuller became the Tribune's literary editor and one of its most important critics. Whitelaw Reid later managed the paper and became a national Republican figure."),
            ("Charles Dana and Karl Marx", "Charles A. Dana served as managing editor before entering Lincoln's War Department, while Karl Marx supplied European correspondence. Those names identify the Tribune's unusually broad reform and international network."),
            ("Associationism", "He gave Albert Brisbane space to promote Charles Fourier's cooperative social system. The connection links him to Brook Farm and other antebellum utopian experiments."),
            ("Labor and homesteads", "He supported workers' organization, land reform, and cheap western farms. His newspaper helped normalize policies that culminated in the Homestead Act."),
            ("Go West correction", "He popularized Go West, young man, but probably did not coin it. The phrase is often credited to John B. L. Soule, whose exact priority remains disputed."),
            ("Seward-Weed-Greeley firm", "He initially cooperated with William Seward and Thurlow Weed in New York Whig politics. A bitter 1854 letter announced the dissolution of their political partnership."),
            ("Spitting on the 1852 platform", "He wrote that he defied, execrated, and spat upon the Whig platform supporting the Compromise of 1850. The quotation appeared in IAC's national playoff route."),
            ("Republican rise and Seward's defeat", "The Tribune helped move antislavery Whigs into the Republican Party. At the 1860 convention, he worked against Seward's nomination, initially favored Edward Bates, and helped clear the path for Abraham Lincoln."),
            ("A brief House term", "After David S. Jackson lost his seat for election fraud, this editor served the final months of the term in 1848-49. He used the position to attack congressional mileage abuses."),
            ("On to Richmond", "Early in the Civil War, the Tribune pressed for an immediate Union advance with the slogan Forward to Richmond. After the First Bull Run disaster, the same editor briefly became deeply pessimistic about continuing the war."),
            ("Prayer of Twenty Millions", "His 1862 open letter demanded stronger enforcement of emancipation policy. Lincoln replied that his paramount object was to save the Union, then issued the preliminary proclamation weeks later."),
            ("Niagara peace mission", "In 1864 he pursued an unauthorized meeting with Confederate representatives in Canada. Lincoln converted the episode into a demand for reunion and abandonment of slavery."),
            ("Jefferson Davis bail", "He signed the former Confederate president's 1867 bail bond with other prominent men. Many longtime readers and Union supporters denounced him for the gesture."),
            ("What I Know of Farming", "His 1871 book collected practical and sometimes eccentric agricultural advice despite his career as an urban editor. The title offers a work clue separate from his newspaper and famous westward slogan."),
            ("Liberal Republican defeat", "In 1872 he ran against Grant with B. Gratz Brown and Democratic endorsement. His wife Mary Cheney Greeley died shortly before the election; he then suffered a breakdown and died before the Electoral College met."),
            ("Rejected electoral votes", "Because he died after the popular vote, electors pledged to him scattered among several alternatives. Congress rejected three Georgia votes still cast for the dead candidate, while most former Greeley electors supported Thomas Hendricks, Benjamin Gratz Brown, or others."),
        ],
        {"6": ["David S. Jackson special election", "1852 platform denunciation", "Georgia electoral votes rejected", "The New-Yorker and Thomas McElrath", "Karl Marx and Charles Dana"], "5": ["Whitelaw Reid and Margaret Fuller", "Prayer of Twenty Millions", "Seward-Weed split", "Niagara peace mission", "Liberal Republican candidacy"], "4": ["New-York Tribune", "Go West, young man", "1872 opponent of Grant", "Jefferson Davis bail", "death before electoral votes"]},
        [("Thurlow Weed", "The party organizer and former ally who managed Seward's political network."), ("William Lloyd Garrison", "The abolitionist editor of the Liberator, more uncompromising on immediate abolition."), ("Whitelaw Reid", "The Tribune lieutenant who later became an ambassador and vice-presidential nominee."), ("Charles A. Dana", "Another Tribune editor who later worked in the War Department and ran the New York Sun.")],
        "IAC: 2018 National History Bowl national playoff round 1, direct answerline",
        "https://www.iacompetitions.com/wp-content/uploads/2023/08/2018-HS-Nationals-History-Bowl-Playoff-Round-1.pdf",
    ),
    lesson(
        "POL-036", "Richard Nixon", "1913-1994 | Thirty-seventh president",
        "A California Quaker who rose through anti-communist investigations, lost narrowly in 1960, returned to win twice, transformed Cold War diplomacy, and resigned over Watergate.",
        [
            ("Yorba Linda and Duke Law", "He grew up in a financially strained Quaker family that operated a grocery and service station in Whittier. A scholarship took him to Duke Law School."),
            ("Navy and South Pacific", "He served as a Navy supply officer during World War II rather than as a combat pilot. Poker winnings helped finance his first congressional campaign, a useful correction to assumptions created by his later Cold War image."),
            ("Voorhis and the Pink Lady", "He defeated congressman Jerry Voorhis in 1946 by stressing communist-linked support, then attacked Helen Gahagan Douglas as the Pink Lady in the 1950 Senate race."),
            ("Alger Hiss and the Pumpkin Papers", "As a House Un-American Activities Committee member, he championed Whittaker Chambers's allegations against Hiss. Microfilm hidden in a hollowed pumpkin became the investigation's famous physical clue."),
            ("Checkers speech", "Accused in 1952 of benefiting from a private political fund, he defended his finances on television and said his daughters would keep a gifted dog named Checkers. Eisenhower retained him on the ticket."),
            ("Eisenhower illnesses", "As vice president he chaired cabinet and National Security Council meetings during Eisenhower's illnesses, but no constitutional transfer of power occurred. Their private disability agreement anticipated the later Twenty-Fifth Amendment."),
            ("Caracas attack", "During a 1958 South American tour, hostile crowds attacked his motorcade in Caracas, Venezuela. The confrontation became one of the episodes later organized in his memoir Six Crises."),
            ("Kitchen Debate", "As vice president he debated Nikita Khrushchev inside an American model kitchen at the 1959 Moscow exhibition, turning consumer goods into Cold War propaganda."),
            ("The 1960 debates", "A knee injury, infection, and poor television appearance hurt him against John Kennedy. Radio listeners were sometimes said to prefer him, though evidence for that famous claim is weak."),
            ("Last press conference", "After losing the 1962 California governor's race to Pat Brown, he told reporters they would not have him to kick around anymore. The apparent farewell made his 1968 comeback more dramatic."),
            ("Southern strategy and Agnew", "His 1968 campaign appealed to voters alienated by civil-rights unrest and Democratic change. He chose Maryland governor Spiro Agnew as his running mate."),
            ("Chennault affair", "Campaign intermediary Anna Chennault urged South Vietnamese officials to resist Johnson administration peace talks in 1968, suggesting they would receive better terms after the election. Nixon denied involvement, and the episode remained hidden from voters."),
            ("Silent Majority", "In a November 1969 television address, he asked the great silent majority to support his Vietnam policy against increasingly visible protests. The phrase became shorthand for his appeal to voters who felt culturally and politically displaced."),
            ("China opening", "Secret diplomacy by Henry Kissinger prepared his 1972 visit to Mao Zedong and Zhou Enlai. The Shanghai Communique acknowledged competing positions over Taiwan."),
            ("Detente and SALT", "He met Leonid Brezhnev and signed the Anti-Ballistic Missile Treaty and interim SALT I agreement. Triangular diplomacy used relations with China to pressure the Soviet Union."),
            ("Vietnamization and Cambodia", "He withdrew U.S. ground forces while expanding South Vietnamese responsibility, but bombing and incursions spread the war into Cambodia. The Paris Peace Accords followed in 1973."),
            ("Domestic surprises", "His administration created the Environmental Protection Agency, signed OSHA and major environmental laws, imposed wage-price controls, and ended dollar convertibility into gold in the Nixon Shock."),
            ("Philadelphia Plan and New Federalism", "His Labor Department enforced affirmative-action goals on federal construction through the Philadelphia Plan. Revenue sharing and block grants formed his New Federalism, while his more ambitious Family Assistance Plan failed in Congress."),
            ("Enemies list and Plumbers", "The White House used an enemies list against political opponents and formed the Plumbers after the Pentagon Papers leak. Operatives later burglarized Daniel Ellsberg's psychiatrist's office, linking secrecy abuses directly to the Watergate culture."),
            ("Six Crises", "His 1962 memoir treated the Hiss case, the fund controversy and Checkers speech, Eisenhower's illnesses, the attack on him in Caracas, the Kitchen Debate, and the 1960 campaign as six tests of character."),
            ("Nixon Agonistes and The Imperial Presidency", "Garry Wills's Nixon Agonistes interpreted the 1968 campaign and his political personality. Arthur Schlesinger Jr.'s The Imperial Presidency used his administration as the culmination of expanding executive power."),
            ("The Final Days", "Bob Woodward and Carl Bernstein reconstructed the administration's collapse in this 1976 book. It follows All the President's Men, which concentrates on their reporting from the break-in through the 1972 election."),
            ("Butterfield and the tapes", "Deputy assistant Alexander Butterfield revealed the taping system during the Senate Watergate hearings. John Dean's testimony, the missing eighteen-and-a-half minutes, and the later smoking-gun tape turned the cover-up into direct presidential evidence."),
            ("Saturday Night Massacre", "He ordered Attorney General Elliot Richardson to fire special prosecutor Archibald Cox; Richardson and deputy William Ruckelshaus resigned, while Solicitor General Robert Bork carried out the dismissal. The crisis sharply increased support for impeachment."),
            ("United States v. Nixon and resignation", "The Supreme Court unanimously rejected an absolute executive-privilege claim and ordered release of the tapes. Facing articles of impeachment, he resigned on August 9, 1974; Gerald Ford later granted a full pardon."),
            ("Frost interviews and rehabilitation", "In 1977 interviews with David Frost, he defended presidential power before offering a qualified apology for betraying the country. He later rebuilt a partial reputation as a foreign-policy writer and adviser without escaping Watergate."),
        ],
        {"6": ["Nixon Agonistes and carpet-beating scene", "Six Crises", "Chennault affair", "Caracas motorcade", "Imperial Presidency"], "5": ["The Final Days", "Woodward and Bernstein", "televised debate details", "Ellsberg psychiatrist burglary", "Butterfield and the taping system"], "4": ["Watergate", "Checkers and Kitchen Debate", "China opening", "thirty-seventh president", "resignation and Ford pardon"]},
        [("Richard Nixon", "The president; Pat Nixon was his wife and a separate first-lady answerline possibility."), ("Alger Hiss", "The accused diplomat whose case launched this politician nationally."), ("Henry Kissinger", "The national security adviser and secretary of state who directed much of the diplomacy."), ("Spiro Agnew", "The vice president who resigned over Maryland bribery unrelated to Watergate.")],
        "IAC: 2019 USHB national playoff round 2, direct answerline",
        "https://www.iacompetitions.com/wp-content/uploads/2023/09/2019-HS-Nationals-US-History-Bee-Playoff-Round-2.pdf",
    ),
    lesson(
        "REF-026", "John Brown", "1800-1859 | Militant abolitionist",
        "A deeply religious abolitionist whose violent campaign in Bleeding Kansas and failed seizure of Harpers Ferry transformed him into either a terrorist or martyr on the eve of the Civil War.",
        [
            ("Owen Brown and the enslaved boy", "His Calvinist father Owen opposed slavery. The younger man later recalled that seeing an enslaved boy beaten helped turn moral opposition into a personal calling."),
            ("Commercial failures", "He tried tanning, land speculation, sheep breeding, and wool brokerage, often failing and accumulating debts. In Springfield he worked with Simon Perkins and encountered a strong Black abolitionist community."),
            ("League of Gileadites", "He organized this group to resist enforcement of the Fugitive Slave Act. Its biblical name and practical rescue plans are excellent early clues."),
            ("North Elba", "Gerrit Smith offered Adirondack land to Black settlers, and this abolitionist moved his family there. He was eventually buried at the North Elba farm."),
            ("Pottawatomie", "After the sack of Lawrence and caning of Charles Sumner, his party killed five proslavery men along Pottawatomie Creek in May 1856. He directed but may not have personally struck the victims."),
            ("Black Jack and Henry Clay Pate", "His force captured proslavery commander Pate at this 1856 clash. A prisoner exchange helped recover two of his sons."),
            ("Osawatomie", "He fought a larger proslavery force near this Kansas settlement, producing the nickname Osawatomie attached to him. A later progressive magazine adopted the same name."),
            ("Tragic Prelude", "John Steuart Curry's Kansas State Capitol mural places him at the center holding a rifle and a Bible before a tornado and prairie fire. The image has already anchored an IAC question."),
            ("Missouri liberation raid", "In December 1858 he led enslaved people out of Missouri, killed one slaveholder, and escorted the group through Iowa to Canada. The operation demonstrated the mobile liberation strategy he hoped to expand from Harpers Ferry."),
            ("The Secret Six", "Thomas Wentworth Higginson, Theodore Parker, Samuel Gridley Howe, Franklin Sanborn, George Luther Stearns, and Gerrit Smith supplied varying degrees of support for his plans."),
            ("Chatham Convention", "At Chatham, Canada West, in 1858, his supporters adopted a provisional constitution for a revolutionary antislavery government. Black activist Martin Delany participated."),
            ("Hugh Forbes and the pikes", "British veteran Hugh Forbes was hired to train the force but exposed the plan after a pay dispute. Connecticut blacksmith Charles Blair manufactured the pikes intended for people who joined the uprising without firearms."),
            ("Douglass and Tubman", "Frederick Douglass met him at Chambersburg and refused to join what he considered a suicidal attack on a federal arsenal. Brown called Harriet Tubman General Tubman and sought her support, but illness kept her from participating."),
            ("Harpers Ferry", "In October 1859 he seized the federal armory hoping enslaved people would join an expanding liberation movement. He took Lewis Washington hostage but became trapped in the engine house."),
            ("Lewis Washington's relics", "The raiders seized George Washington's great-grandnephew Lewis Washington along with a sword presented by Frederick the Great and pistols associated with Lafayette. Those objects create unusually specific opening clues."),
            ("Kagi, Newby, Oliver, and Watson", "John Henry Kagi and Dangerfield Newby died in the raid, as did his sons Oliver and Watson. Remembering the small raider network distinguishes deep clues from the generic event."),
            ("Heyward Shepherd", "Free Black railroad baggage master Heyward Shepherd became the raid's first fatality when shot by Brown's men. His death complicated later claims about whom the raid represented and inspired a controversial memorial at Harpers Ferry."),
            ("Lee, Stuart, and Israel Greene", "Colonel Robert E. Lee commanded the response, J. E. B. Stuart delivered the surrender demand, and Marine lieutenant Israel Greene helped storm the engine house."),
            ("Isaac Smith and the Virginia trial", "He had rented the nearby Kennedy Farm under the alias Isaac Smith. At Charles Town, Judge Richard Parker presided, Andrew Hunter prosecuted, Governor Henry Wise rejected pleas for delay, and Lewis Washington testified."),
            ("Silas Soule and Year of Meteors", "After the raid, Kansas friend Silas Soule offered to break him out of the Charles Town jail and flee north to New York or Canada; he refused, believing his execution would better serve abolition. Walt Whitman's Year of Meteors remembered him simply as an old man escorted to execution."),
            ("Victor Hugo and Lydia Maria Child", "Victor Hugo compared Virginia's execution to Washington killing Spartacus, while Lydia Maria Child publicly defended the prisoner and offered nursing aid. Their interventions helped transform a defeated raider into an international martyr."),
            ("Execution witnesses", "Thomas J. Jackson brought VMI cadets to guard the execution, and actor John Wilkes Booth attended in a militia uniform. The future Stonewall Jackson and Lincoln assassin form a memorable 1859 convergence."),
            ("Trial, speech, and final note", "Virginia convicted him of treason, murder, and inciting slave revolt. His courtroom speech accepted death for acting on behalf of the enslaved; a separate note on execution day predicted that slavery's crimes would be purged only with blood."),
            ("John Brown's Body", "Union soldiers transformed the name into a marching song, and Julia Ward Howe wrote Battle Hymn of the Republic to its tune. Keep the historical person separate from the song title when IAC asks for a work."),
        ],
        {"6": ["Silas Soule and Whitman poem", "Kagi, Newby, Oliver, and Watson", "Lewis Washington's sword and pistols", "Hugh Forbes and Charles Blair pikes", "Secret Six and Victor Hugo"], "5": ["Pottawatomie", "Battle of Black Jack", "Chatham constitution", "Missouri liberation raid", "Tragic Prelude"], "4": ["Harpers Ferry armory", "Lee and J. E. B. Stuart", "militant abolitionist", "execution in 1859", "John Brown's Body"]},
        [("John Brown", "The abolitionist; do not confuse him with the song John Brown's Body."), ("John Brown's Body", "The marching song later inspired Julia Ward Howe's Battle Hymn of the Republic."), ("Nat Turner", "Turner led an enslaved uprising in Virginia in 1831 rather than a white abolitionist raid in 1859."), ("Denmark Vesey", "Vesey was accused of planning an 1822 Charleston uprising.")],
        "IAC: 2021 USHB regional semifinal direct answerline and repeated national preliminaries",
        "https://www.iacompetitions.com/wp-content/uploads/2023/09/2020-2021-HS-US-History-Bee-Semifinals-B-Set.pdf",
    ),
    lesson(
        "POL-037", "Charles Evans Hughes", "1862-1948 | Governor, nominee, diplomat, chief justice",
        "A reform governor and almost-president who served twice on the Supreme Court, ran against Wilson in 1916, organized naval diplomacy, and presided over the constitutional revolution of 1937.",
        [
            ("Baptist household and law", "Born in Glens Falls, New York, to a Baptist minister, he graduated from Brown and Columbia Law. His intense preparation and beard became recognizable public traits."),
            ("Armstrong investigation", "His questioning in the 1905 New York legislative investigation exposed insurance-company abuses involving campaign contributions and self-dealing. The performance launched him into electoral politics."),
            ("Governor of New York", "Elected over newspaper publisher William Randolph Hearst in 1906, he strengthened public-service regulation, fought racetrack gambling, and resisted Republican machine control. Theodore Roosevelt supported him despite policy tensions."),
            ("First Supreme Court service", "William Howard Taft appointed him associate justice in 1910. He resigned in 1916 to accept the Republican presidential nomination."),
            ("First-term opinions", "Before resigning, he joined the Court's rejection of peonage in Bailey v. Alabama and wrote the Shreveport Rate Cases opinion allowing federal regulation of intrastate rail rates that burdened interstate commerce."),
            ("The 1916 near victory", "Running with Charles W. Fairbanks, he lost to Woodrow Wilson by only twenty-three electoral votes. California's thirteen votes would have reversed the outcome; a famous story blamed his failure to greet Governor Hiram Johnson, though the defeat had broader causes."),
            ("Secretary of state", "Under Harding and Coolidge he defended an internationalist foreign policy without joining the League of Nations. He pursued arbitration, debt diplomacy, and the Open Door in China."),
            ("Washington Naval Conference", "He opened the 1921 conference by proposing large-scale scrapping of capital ships. His proposal led into the Four-Power, Five-Power, and Nine-Power treaties."),
            ("Hughes-Peynado plan", "His State Department worked with Dominican diplomat Francisco Peynado on a 1922 agreement establishing steps toward elections and the end of the U.S. occupation. The resulting plan is a difficult Caribbean-diplomacy route."),
            ("World Court and private practice", "He advocated U.S. participation in the Permanent Court of International Justice and later returned to elite legal practice before becoming chief justice."),
            ("Chief justice after Taft", "Herbert Hoover appointed him in 1930. His son, Charles Evans Hughes Jr., resigned as solicitor general to avoid arguing before his father's Court."),
            ("Near v. Minnesota", "He wrote the 1931 majority applying freedom of the press against state prior restraints. This liberal ruling complicates any simple description of him as conservative."),
            ("Norris v. Alabama", "He wrote the 1935 decision overturning a Scottsboro defendant's conviction because Alabama had systematically excluded Black citizens from juries. The case links him to the Scottsboro Boys without making him their trial lawyer."),
            ("Schechter Poultry", "His unanimous opinion invalidated the National Industrial Recovery Act's code system for excessive delegation and effects outside interstate commerce."),
            ("Four Horsemen and Three Musketeers", "He and Owen Roberts occupied the Court's center between conservative and liberal blocs. Their votes became decisive in New Deal constitutional cases."),
            ("Blaisdell and constitutional adaptation", "In Home Building & Loan v. Blaisdell, he upheld Minnesota's temporary mortgage moratorium despite the Contract Clause. The opinion argued that constitutional restraints must be read in light of genuine emergencies."),
            ("West Coast Hotel", "His 1937 majority upheld Washington's minimum wage for women and abandoned the Lochner-era treatment of liberty of contract. Owen Roberts supplied the pivotal vote in the switch in time, while Hughes wrote the opinion."),
            ("Court-packing and the 1937 shift", "He rebutted Roosevelt's claim that the Court was behind on work in a letter to Burton Wheeler, drawing supporting information from Justice Louis Brandeis. He then led majorities sustaining labor and Social Security laws after the constitutional shift."),
            ("Jones & Laughlin and Social Security", "After the minimum-wage pivot in West Coast Hotel, he wrote NLRB v. Jones & Laughlin Steel upholding federal labor regulation. He also joined the 1937 majorities sustaining unemployment compensation in Steward Machine and old-age benefits in Helvering v. Davis."),
        ],
        {"6": ["son's solicitor-general resignation", "Armstrong insurance investigation", "Hughes-Peynado plan", "Shreveport Rate Cases", "Norris v. Alabama"], "5": ["Near v. Minnesota", "Schechter Poultry", "Hughes and Roberts between Court blocs", "Washington Conference", "Blaisdell emergency reasoning"], "4": ["1916 nominee", "Harding secretary of state", "chief justice through the 1930s", "court-packing fight", "Jones & Laughlin and Social Security"]},
        [("Charles Evans Hughes Jr.", "The son was solicitor general and resigned when his father became chief justice."), ("Owen Roberts", "The swing justice associated with the switch in time, not the chief justice."), ("William Howard Taft", "The former president and chief justice whom this jurist succeeded."), ("Harlan Fiske Stone", "The justice who succeeded him as chief justice in 1941.")],
        "IAC: 2019 USHB national playoff round 2, direct answerline",
        "https://www.iacompetitions.com/wp-content/uploads/2023/09/2019-HS-Nationals-US-History-Bee-Playoff-Round-2.pdf",
    ),
    lesson(
        "POL-038", "John Quincy Adams", "1767-1848 | Diplomat, president, congressman",
        "The extraordinarily experienced diplomat who became sixth president through the disputed election of 1824, then built a more consequential post-presidential career fighting slavery in the House.",
        [
            ("Bunker Hill from Penn's Hill", "As a child he watched smoke from the Battle of Bunker Hill with his mother Abigail. His childhood letters reveal the pressure of growing up in a revolutionary political family."),
            ("The diary", "He kept an enormous diary from youth until shortly before his death, recording diplomacy, politics, exercise, family conflict, and his own moral failures. It is one of the richest continuous personal records in American political history."),
            ("Francis Dana and Russia", "As a teenager he served as secretary and interpreter for diplomat Francis Dana's mission to Catherine the Great's Russia. He later studied at Leiden and graduated from Harvard."),
            ("Netherlands and Prussia", "Washington appointed him minister to the Netherlands, and his father later sent him to Prussia. He negotiated a Prussian commercial treaty before returning to the United States."),
            ("Louisa Catherine Johnson", "He married the London-born daughter of an American merchant while serving abroad. She remains the only first lady born outside the United States or its colonies."),
            ("Federalist senator who broke ranks", "He supported Jefferson's Louisiana Purchase and embargo despite Federalist opposition. The break ended his Massachusetts Senate career but helped Madison appoint him minister to Russia."),
            ("Minister during Napoleon's invasion", "He was in St. Petersburg when Napoleon invaded Russia in 1812 and developed a productive relationship with Tsar Alexander I."),
            ("Treaty of Ghent", "He joined Henry Clay, Albert Gallatin, James Bayard, and Jonathan Russell in negotiating the treaty ending the War of 1812."),
            ("Monroe's secretary of state", "He negotiated the Adams-Onis Treaty, helped formulate the Monroe Doctrine, and supported the Convention of 1818 and Rush-Bagot limitations with Britain."),
            ("Adams-Onis details", "The 1819 treaty acquired Florida, fixed a transcontinental boundary to the Pacific, and had the United States renounce claims to Texas. Spanish minister Luis de Onis was his negotiating counterpart."),
            ("Canning and the Monroe Doctrine", "He opposed issuing a joint declaration with British foreign secretary George Canning, arguing that America should not come in as a cockboat in the wake of a British man-of-war. His advice helped produce Monroe's unilateral 1823 doctrine."),
            ("The corrupt bargain", "After no candidate won an electoral majority in 1824, the House selected him over Andrew Jackson. His appointment of Henry Clay as secretary of state generated the enduring accusation."),
            ("Lighthouses of the skies", "His ambitious national program included roads, canals, scientific exploration, a national university, and an astronomical observatory. Opponents mocked the observatory phrase."),
            ("C and O Canal groundbreaking", "He endorsed national roads, canals, and scientific development but faced a hostile Jacksonian Congress. On July 4, 1828, he dug the first earth for the Chesapeake and Ohio Canal while Charles Carroll separately laid the Baltimore and Ohio Railroad's first stone."),
            ("The pool table", "Jacksonians portrayed his purchase of a billiard table with personal funds as aristocratic extravagance. The minor controversy illustrates the relentless opposition to his presidency."),
            ("David Porter and Fajardo", "He court-martialed naval hero David Porter after Porter landed forces at Fajardo, Puerto Rico, to demand redress for an officer's detention. The obscure Caribbean episode has opened an IAC question on his presidency."),
            ("Poinsett and the Panama Congress", "He appointed Joel Roberts Poinsett minister to Mexico and sought delegates to Simon Bolivar's 1826 Congress of Panama. Southern and Jacksonian opposition delayed the mission until participation became meaningless."),
            ("Old Man Eloquent", "Returning to the House in 1831, he fought the gag rule that automatically tabled antislavery petitions. Congress finally repealed it in 1844."),
            ("Petitions and the gag rule", "He repeatedly forced antislavery petitions onto the House agenda, sometimes provoking days of procedural combat. Opponents attempted to censure him after he presented a petition from enslaved people, but he turned the proceeding against them."),
            ("The Amistad argument", "He argued before the Supreme Court for the freedom of the African captives in 1841. His lengthy presentation invoked natural rights and the Declaration."),
            ("George Washington Adams", "His troubled eldest son disappeared from the steamship Benjamin Franklin in 1829 and was presumed to have died by suicide. IAC has used the ship and disappearance as an early presidential-biography clue."),
            ("Smithsonian", "He chaired the House committee that directed James Smithson's bequest toward a national scientific institution and served on the Smithsonian's first Board of Regents. The role joined his congressional career to his lifelong support for science."),
            ("Mexican War opposition and final collapse", "He denounced annexation and the Mexican-American War as extensions of slave power. In 1848 he collapsed in the House after voting against honors for Mexican War officers and died in the Speaker's Room after saying this is the last of Earth."),
        ],
        {"6": ["George Washington Adams and the Benjamin Franklin", "David Porter at Fajardo", "cockboat and Canning", "collapse over Mexican War honors", "James Smithson's bequest"], "5": ["Francis Dana and first minister to Russia", "Adams-Onis boundary", "post-presidential House career", "gag-rule petitions", "Amistad argument"], "4": ["corrupt bargain with Clay", "Monroe Doctrine", "Old Man Eloquent", "sixth president", "son of the second president"]},
        [("John Adams", "The father was the second president and never returned to Congress afterward."), ("John Quincy Adams", "The son was the sixth president, diplomat, and antislavery representative."), ("Henry Clay", "The House speaker who backed him in 1824 and became secretary of state."), ("Andrew Jackson", "The 1824 plurality winner who defeated him in the bitter 1828 rematch.")],
        "IAC: 2015 National History Bee finals, direct answerline",
        "https://www.iacompetitions.com/wp-content/uploads/2023/08/2015-HS-Nationals-History-Bee-Finals.pdf",
    ),
    lesson(
        "POL-039", "James K. Polk", "1795-1849 | Eleventh president",
        "A Tennessee Jacksonian and surprise 1844 nominee who achieved nearly every stated policy goal by cutting tariffs, restoring an independent treasury, settling Oregon, and acquiring the Mexican Cession.",
        [
            ("McDowell's surgery", "As a teenager he underwent dangerous surgery for urinary stones by pioneering Kentucky surgeon Ephraim McDowell, without modern anesthesia or antisepsis. The operation may have left him infertile."),
            ("University of North Carolina", "He graduated in 1818, studied law under Felix Grundy, and entered Tennessee politics as an ally of Andrew Jackson."),
            ("Sarah Childress Polk", "He married the well-educated Sarah Childress in 1824. She served as his political partner and White House hostess, enforced a restrained Presbyterian social style, and survived him by more than forty years."),
            ("Young Hickory", "This nickname advertised him as Jackson's disciplined protege. Unlike Jackson, he was an exacting administrator who closely supervised cabinet departments."),
            ("Speaker of the House", "He defeated fellow Tennessean John Bell for the speakership and served from 1835 to 1839, remaining the only House speaker to become president. He defended Jacksonian policies during the Bank and slavery-petition conflicts."),
            ("Tennessee defeats", "After one gubernatorial victory, he lost reelection to James C. Jones and lost again in 1843. Those defeats made his sudden national nomination more surprising."),
            ("The first dark horse", "At the 1844 Democratic convention, Martin Van Buren's resistance to immediate Texas annexation blocked him. The convention turned to this compromise candidate on the ninth ballot."),
            ("Who is James K. Polk?", "Whigs used the question to mock his obscurity. He ran with George M. Dallas against Henry Clay while linking Texas annexation to claims in Oregon."),
            ("Texas annexation handoff", "Congress approved annexation by joint resolution in Tyler's final days. Polk allowed Tyler to send the offer immediately rather than withdraw it, so Texas entered the Union during Polk's first year even though the decisive resolution preceded him."),
            ("Four major goals", "He sought a lower tariff, restoration of the independent treasury, settlement of the Oregon boundary, and acquisition of California. By one term's end he had achieved all four."),
            ("Cabinet map", "James Buchanan served as secretary of state, Robert J. Walker at Treasury, George Bancroft at Navy, William L. Marcy at War, Cave Johnson as postmaster general, and John Y. Mason as attorney general. Those names divide his territorial, fiscal, and military clue routes."),
            ("Walker Tariff and Independent Treasury", "Treasury Secretary Robert J. Walker designed the lower 1846 tariff, while the Independent Treasury Act restored federal custody of government funds outside private banks. Together they fulfilled half of his four-part domestic program."),
            ("Oregon and forty-nine", "Campaign expansionists demanded all territory to latitude 54 degrees 40 minutes, but the 1846 Oregon Treaty compromised with Britain largely along the forty-ninth parallel."),
            ("Slidell and the disputed border", "After Mexico rejected envoy John Slidell's purchase offer, he ordered Zachary Taylor into territory between the Nueces and Rio Grande claimed by both countries."),
            ("Thornton and the Spot Resolutions", "The Thornton clash allowed him to claim that American blood had been shed on American soil. Abraham Lincoln demanded the exact spot, challenging the war's justification."),
            ("Taylor, Scott, and Mexico City", "After Taylor's victories produced a potential Whig rival, the administration transferred many experienced troops to Winfield Scott. Scott's Veracruz-to-Mexico City campaign finally compelled negotiations."),
            ("Wilmot Proviso", "David Wilmot repeatedly attached a slavery ban to appropriations for territory acquired from Mexico. It never became law, but it exposed the sectional consequences of the expansion Polk had achieved."),
            ("Trist and Guadalupe Hidalgo", "He recalled diplomat Nicholas Trist, but Trist ignored the order and completed the 1848 treaty. Mexico ceded vast western territory for fifteen million dollars."),
            ("River and Harbor veto", "In 1846 he vetoed an internal-improvements bill containing many local projects, arguing that federal spending required a genuinely national purpose. The veto is a useful policy clue distinct from territorial expansion."),
            ("Dixon Lewis and the treasury bill", "Alabama senator Dixon Hall Lewis managed the Independent Treasury measure in the Senate and was a close administration ally. That less familiar name can identify the president through his domestic program."),
            ("Gold in California", "Near the end of 1848, he confirmed reports of California gold in his annual message and displayed evidence sent to Washington. The rush transformed territory acquired by his war just as his presidency ended."),
            ("One term and 103 days", "He honored his pledge not to seek reelection and died of cholera only 103 days after leaving office, the shortest retirement of any president."),
        ],
        {"6": ["Dixon Lewis and treasury policy", "river-and-harbor veto", "McDowell surgery", "Sarah Childress", "James K. Jones defeats"], "5": ["Spot Resolutions", "dark-horse ninth ballot", "Walker Tariff and Independent Treasury", "Slidell mission", "cabinet map"], "4": ["Mexican-American War", "Oregon settlement", "Texas annexation", "four stated goals", "eleventh president"]},
        [("James K. Polk", "The expansionist president; Leonidas Polk was his distant cousin and a Confederate bishop-general."), ("Zachary Taylor", "The general sent to the Rio Grande who later became president."), ("Nicholas Trist", "The diplomat who completed the peace treaty despite being recalled."), ("George M. Dallas", "The vice president and 1844 running mate.")],
        "IAC: 2017 National History Bowl national playoff round 1, direct answerline",
        "https://www.iacompetitions.com/wp-content/uploads/2023/08/2017-HS-Nationals-History-Bowl-Playoff-Round-1.pdf",
    ),
    lesson(
        "REL-012", "Anne Hutchinson", "1591-1643 | Puritan dissenter",
        "A skilled midwife and religious teacher whose challenge to Massachusetts ministers produced the Antinomian Controversy, banishment to Rhode Island, and death during Kieft's War in New Netherland.",
        [
            ("Francis Marbury", "Her father was an English clergyman repeatedly punished for criticizing poorly educated bishops and ministers. His defiance supplied a family model for challenging religious authority."),
            ("John Cotton and Boston", "She followed minister John Cotton to Massachusetts in 1634. Her household's status and her work as a midwife gave her unusual access across the community."),
            ("William Hutchinson and fifteen children", "She married cloth merchant William Hutchinson and bore fifteen children. The family followed Cotton from England, and its wealth helped turn her home meetings into a colony-wide political problem."),
            ("Meetings for women and men", "She began by discussing sermons with women, then attracted mixed gatherings that could include dozens of listeners. Authorities feared an alternative center of religious influence."),
            ("Covenant of grace", "She emphasized salvation through God's freely given grace and accused most colony ministers of preaching a covenant of works. Cotton was the principal minister she exempted."),
            ("Henry Vane", "The young governor supported the grace faction, while John Winthrop and Thomas Dudley opposed it. Vane lost political control and returned to England."),
            ("John Wheelwright", "Her brother-in-law's fast-day sermon attacked the opposing ministers. His conviction for sedition turned theological disagreement into a political crisis."),
            ("Antinomian or Free Grace Controversy", "Opponents called her followers antinomians, implying that inward grace freed them from moral law. Supporters preferred free grace and rejected the accusation."),
            ("The 1637 election and disarming", "At the contentious Newtown election, John Winthrop defeated Henry Vane and returned as governor. Authorities later disarmed or disfranchised many Hutchinson supporters, turning theology into a struggle over political control."),
            ("Newtown synod", "A 1637 gathering of ministers condemned more than eighty supposed theological errors associated with the free-grace faction. The synod isolated her before the civil court convened."),
            ("The 1637 civil trial", "At Newtown she answered Winthrop and Dudley skillfully until claiming direct revelation from God. That claim gave magistrates grounds to convict and banish her."),
            ("Church trial and John Cotton's break", "At the 1638 church proceeding, Cotton withdrew support and the Boston congregation excommunicated her. Civil banishment and church excommunication were separate actions."),
            ("Portsmouth and the Aquidneck Compact", "William Coddington, her husband William, and other supporters founded Pocasset, later Portsmouth, on Aquidneck Island. The settlement joined Rhode Island."),
            ("Mary Dyer and the monstrous births", "She helped conceal Mary Dyer's severely malformed stillbirth, and later suffered an abnormal pregnancy herself. Winthrop publicized both as supposed divine judgments."),
            ("Pelham Bay and the Siwanoy", "After her husband died, she moved beyond Massachusetts authority into New Netherland. Siwanoy warriors killed her and most of her household in 1643 during Kieft's War; daughter Susanna survived."),
            ("Split Rock and Susanna", "The attack occurred near today's Pelham Bay and is associated with Split Rock. Nine-year-old Susanna Hutchinson was taken captive and later returned, becoming the only household survivor."),
            ("Wampage and place names", "Tradition says Siwanoy leader Wampage took a name associated with her after the attack. The Hutchinson River and parkway preserve her surname near the death site."),
        ],
        {"6": ["Wampage naming tradition", "Split Rock and Susanna", "Newtown synod's condemned errors", "Thomas Dudley and John Cotton theology", "Mary Dyer's concealed stillbirth"], "5": ["covenant of grace", "Antinomian trial", "Henry Vane and Wheelwright", "1637 election and disarming", "Aquidneck Compact"], "4": ["Portsmouth", "Rhode Island exile", "John Winthrop trial", "Free Grace Controversy", "banished from Massachusetts Bay"]},
        [("Anne Hutchinson", "The lay teacher banished during the Antinomian Controversy."), ("Mary Dyer", "The follower who became a Quaker and was executed in Boston in 1660."), ("Roger Williams", "The minister banished earlier over church-state and Indigenous-land issues."), ("John Cotton", "The minister whose grace theology inspired her before he withdrew support.")],
        "IAC: 2020 National History Bee national semifinals, direct answerline",
        "https://www.iacompetitions.com/wp-content/uploads/2023/08/2020-HS-Nationals-History-Bee-Semifinals.pdf",
    ),
]
